//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakymLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakymLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ConsoleUtil_Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConsoleUtil_Pause {
            get {
                return ResourceManager.GetString("ConsoleUtil_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ConsoleUtil_ReadPassword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConsoleUtil_ReadPassword {
            get {
                return ResourceManager.GetString("ConsoleUtil_ReadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DisposableBase_ObjectDisposedException_IsDisposing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisposableBase_ObjectDisposedException_IsDisposing {
            get {
                return ResourceManager.GetString("DisposableBase_ObjectDisposedException_IsDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ErrorHelper_EnsureWithinClosedRange {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorHelper_EnsureWithinClosedRange {
            get {
                return ResourceManager.GetString("ErrorHelper_EnsureWithinClosedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ErrorHelper_EnsureWithinOpenRange {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorHelper_EnsureWithinOpenRange {
            get {
                return ResourceManager.GetString("ErrorHelper_EnsureWithinOpenRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidPathFormatException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPathFormatException {
            get {
                return ResourceManager.GetString("InvalidPathFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PathString_EnsureFileSystemInfo_IOException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathString_EnsureFileSystemInfo_IOException {
            get {
                return ResourceManager.GetString("PathString_EnsureFileSystemInfo_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SecureStringExtensions_SecurityException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SecureStringExtensions_SecurityException {
            get {
                return ResourceManager.GetString("SecureStringExtensions_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SerializationInfoExtensions_SerializationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SerializationInfoExtensions_SerializationException {
            get {
                return ResourceManager.GetString("SerializationInfoExtensions_SerializationException", resourceCulture);
            }
        }
    }
}
