# ***********************************************************
# * TakymLib                                                *
# * Copyright (C) 2020-2021 Yigty.ORG; all rights reserved. *
# * Copyright (C) 2020-2021 Takym.                          *
# *                                                         *
# * distributed under the MIT License.                      *
# ***********************************************************

custom: https://github.com/YigtyORG/Yigty.ORG/blob/main/DONATION.md
