/****
 * TakymLib
 * Copyright (C) 2020-2021 Yigty.ORG; all rights reserved.
 * Copyright (C) 2020-2021 Takym.
 *
 * distributed under the MIT License.
****/

namespace TakymLib.Text.Internals
{
	/// <remarks>
	///  The Unicode Consortium が定める<see href="http://www.unicode.org/terms_of_use.html">利用規約</see>に従って利用してください。
	/// </remarks>
	internal sealed class EAW12_1_0 : EastAsianWidth
	{
		internal static readonly EAW12_1_0 Instance = new();

		private EAW12_1_0() { }

		public override EastAsianWidthType GetCharType(char c)
		{
			return c switch {
				>= '\u0000' and <= '\u001F' => EastAsianWidthType.Neutral,
				'\u0020' => EastAsianWidthType.Narrow,
				>= '\u0021' and <= '\u0023' => EastAsianWidthType.Narrow,
				'\u0024' => EastAsianWidthType.Narrow,
				>= '\u0025' and <= '\u0027' => EastAsianWidthType.Narrow,
				'\u0028' => EastAsianWidthType.Narrow,
				'\u0029' => EastAsianWidthType.Narrow,
				'\u002A' => EastAsianWidthType.Narrow,
				'\u002B' => EastAsianWidthType.Narrow,
				'\u002C' => EastAsianWidthType.Narrow,
				'\u002D' => EastAsianWidthType.Narrow,
				>= '\u002E' and <= '\u002F' => EastAsianWidthType.Narrow,
				>= '\u0030' and <= '\u0039' => EastAsianWidthType.Narrow,
				>= '\u003A' and <= '\u003B' => EastAsianWidthType.Narrow,
				>= '\u003C' and <= '\u003E' => EastAsianWidthType.Narrow,
				>= '\u003F' and <= '\u0040' => EastAsianWidthType.Narrow,
				>= '\u0041' and <= '\u005A' => EastAsianWidthType.Narrow,
				'\u005B' => EastAsianWidthType.Narrow,
				'\u005C' => EastAsianWidthType.Narrow,
				'\u005D' => EastAsianWidthType.Narrow,
				'\u005E' => EastAsianWidthType.Narrow,
				'\u005F' => EastAsianWidthType.Narrow,
				'\u0060' => EastAsianWidthType.Narrow,
				>= '\u0061' and <= '\u007A' => EastAsianWidthType.Narrow,
				'\u007B' => EastAsianWidthType.Narrow,
				'\u007C' => EastAsianWidthType.Narrow,
				'\u007D' => EastAsianWidthType.Narrow,
				'\u007E' => EastAsianWidthType.Narrow,
				'\u007F' => EastAsianWidthType.Neutral,
				>= '\u0080' and <= '\u009F' => EastAsianWidthType.Neutral,
				'\u00A0' => EastAsianWidthType.Neutral,
				'\u00A1' => EastAsianWidthType.Ambiguous,
				>= '\u00A2' and <= '\u00A3' => EastAsianWidthType.Narrow,
				'\u00A4' => EastAsianWidthType.Ambiguous,
				'\u00A5' => EastAsianWidthType.Narrow,
				'\u00A6' => EastAsianWidthType.Narrow,
				'\u00A7' => EastAsianWidthType.Ambiguous,
				'\u00A8' => EastAsianWidthType.Ambiguous,
				'\u00A9' => EastAsianWidthType.Neutral,
				'\u00AA' => EastAsianWidthType.Ambiguous,
				'\u00AB' => EastAsianWidthType.Neutral,
				'\u00AC' => EastAsianWidthType.Narrow,
				'\u00AD' => EastAsianWidthType.Ambiguous,
				'\u00AE' => EastAsianWidthType.Ambiguous,
				'\u00AF' => EastAsianWidthType.Narrow,
				'\u00B0' => EastAsianWidthType.Ambiguous,
				'\u00B1' => EastAsianWidthType.Ambiguous,
				>= '\u00B2' and <= '\u00B3' => EastAsianWidthType.Ambiguous,
				'\u00B4' => EastAsianWidthType.Ambiguous,
				'\u00B5' => EastAsianWidthType.Neutral,
				>= '\u00B6' and <= '\u00B7' => EastAsianWidthType.Ambiguous,
				'\u00B8' => EastAsianWidthType.Ambiguous,
				'\u00B9' => EastAsianWidthType.Ambiguous,
				'\u00BA' => EastAsianWidthType.Ambiguous,
				'\u00BB' => EastAsianWidthType.Neutral,
				>= '\u00BC' and <= '\u00BE' => EastAsianWidthType.Ambiguous,
				'\u00BF' => EastAsianWidthType.Ambiguous,
				>= '\u00C0' and <= '\u00C5' => EastAsianWidthType.Neutral,
				'\u00C6' => EastAsianWidthType.Ambiguous,
				>= '\u00C7' and <= '\u00CF' => EastAsianWidthType.Neutral,
				'\u00D0' => EastAsianWidthType.Ambiguous,
				>= '\u00D1' and <= '\u00D6' => EastAsianWidthType.Neutral,
				'\u00D7' => EastAsianWidthType.Ambiguous,
				'\u00D8' => EastAsianWidthType.Ambiguous,
				>= '\u00D9' and <= '\u00DD' => EastAsianWidthType.Neutral,
				>= '\u00DE' and <= '\u00E1' => EastAsianWidthType.Ambiguous,
				>= '\u00E2' and <= '\u00E5' => EastAsianWidthType.Neutral,
				'\u00E6' => EastAsianWidthType.Ambiguous,
				'\u00E7' => EastAsianWidthType.Neutral,
				>= '\u00E8' and <= '\u00EA' => EastAsianWidthType.Ambiguous,
				'\u00EB' => EastAsianWidthType.Neutral,
				>= '\u00EC' and <= '\u00ED' => EastAsianWidthType.Ambiguous,
				>= '\u00EE' and <= '\u00EF' => EastAsianWidthType.Neutral,
				'\u00F0' => EastAsianWidthType.Ambiguous,
				'\u00F1' => EastAsianWidthType.Neutral,
				>= '\u00F2' and <= '\u00F3' => EastAsianWidthType.Ambiguous,
				>= '\u00F4' and <= '\u00F6' => EastAsianWidthType.Neutral,
				'\u00F7' => EastAsianWidthType.Ambiguous,
				>= '\u00F8' and <= '\u00FA' => EastAsianWidthType.Ambiguous,
				'\u00FB' => EastAsianWidthType.Neutral,
				'\u00FC' => EastAsianWidthType.Ambiguous,
				'\u00FD' => EastAsianWidthType.Neutral,
				'\u00FE' => EastAsianWidthType.Ambiguous,
				'\u00FF' => EastAsianWidthType.Neutral,
				'\u0100' => EastAsianWidthType.Neutral,
				'\u0101' => EastAsianWidthType.Ambiguous,
				>= '\u0102' and <= '\u0110' => EastAsianWidthType.Neutral,
				'\u0111' => EastAsianWidthType.Ambiguous,
				'\u0112' => EastAsianWidthType.Neutral,
				'\u0113' => EastAsianWidthType.Ambiguous,
				>= '\u0114' and <= '\u011A' => EastAsianWidthType.Neutral,
				'\u011B' => EastAsianWidthType.Ambiguous,
				>= '\u011C' and <= '\u0125' => EastAsianWidthType.Neutral,
				>= '\u0126' and <= '\u0127' => EastAsianWidthType.Ambiguous,
				>= '\u0128' and <= '\u012A' => EastAsianWidthType.Neutral,
				'\u012B' => EastAsianWidthType.Ambiguous,
				>= '\u012C' and <= '\u0130' => EastAsianWidthType.Neutral,
				>= '\u0131' and <= '\u0133' => EastAsianWidthType.Ambiguous,
				>= '\u0134' and <= '\u0137' => EastAsianWidthType.Neutral,
				'\u0138' => EastAsianWidthType.Ambiguous,
				>= '\u0139' and <= '\u013E' => EastAsianWidthType.Neutral,
				>= '\u013F' and <= '\u0142' => EastAsianWidthType.Ambiguous,
				'\u0143' => EastAsianWidthType.Neutral,
				'\u0144' => EastAsianWidthType.Ambiguous,
				>= '\u0145' and <= '\u0147' => EastAsianWidthType.Neutral,
				>= '\u0148' and <= '\u014B' => EastAsianWidthType.Ambiguous,
				'\u014C' => EastAsianWidthType.Neutral,
				'\u014D' => EastAsianWidthType.Ambiguous,
				>= '\u014E' and <= '\u0151' => EastAsianWidthType.Neutral,
				>= '\u0152' and <= '\u0153' => EastAsianWidthType.Ambiguous,
				>= '\u0154' and <= '\u0165' => EastAsianWidthType.Neutral,
				>= '\u0166' and <= '\u0167' => EastAsianWidthType.Ambiguous,
				>= '\u0168' and <= '\u016A' => EastAsianWidthType.Neutral,
				'\u016B' => EastAsianWidthType.Ambiguous,
				>= '\u016C' and <= '\u017F' => EastAsianWidthType.Neutral,
				>= '\u0180' and <= '\u01BA' => EastAsianWidthType.Neutral,
				'\u01BB' => EastAsianWidthType.Neutral,
				>= '\u01BC' and <= '\u01BF' => EastAsianWidthType.Neutral,
				>= '\u01C0' and <= '\u01C3' => EastAsianWidthType.Neutral,
				>= '\u01C4' and <= '\u01CD' => EastAsianWidthType.Neutral,
				'\u01CE' => EastAsianWidthType.Ambiguous,
				'\u01CF' => EastAsianWidthType.Neutral,
				'\u01D0' => EastAsianWidthType.Ambiguous,
				'\u01D1' => EastAsianWidthType.Neutral,
				'\u01D2' => EastAsianWidthType.Ambiguous,
				'\u01D3' => EastAsianWidthType.Neutral,
				'\u01D4' => EastAsianWidthType.Ambiguous,
				'\u01D5' => EastAsianWidthType.Neutral,
				'\u01D6' => EastAsianWidthType.Ambiguous,
				'\u01D7' => EastAsianWidthType.Neutral,
				'\u01D8' => EastAsianWidthType.Ambiguous,
				'\u01D9' => EastAsianWidthType.Neutral,
				'\u01DA' => EastAsianWidthType.Ambiguous,
				'\u01DB' => EastAsianWidthType.Neutral,
				'\u01DC' => EastAsianWidthType.Ambiguous,
				>= '\u01DD' and <= '\u024F' => EastAsianWidthType.Neutral,
				'\u0250' => EastAsianWidthType.Neutral,
				'\u0251' => EastAsianWidthType.Ambiguous,
				>= '\u0252' and <= '\u0260' => EastAsianWidthType.Neutral,
				'\u0261' => EastAsianWidthType.Ambiguous,
				>= '\u0262' and <= '\u0293' => EastAsianWidthType.Neutral,
				'\u0294' => EastAsianWidthType.Neutral,
				>= '\u0295' and <= '\u02AF' => EastAsianWidthType.Neutral,
				>= '\u02B0' and <= '\u02C1' => EastAsianWidthType.Neutral,
				>= '\u02C2' and <= '\u02C3' => EastAsianWidthType.Neutral,
				'\u02C4' => EastAsianWidthType.Ambiguous,
				'\u02C5' => EastAsianWidthType.Neutral,
				'\u02C6' => EastAsianWidthType.Neutral,
				'\u02C7' => EastAsianWidthType.Ambiguous,
				'\u02C8' => EastAsianWidthType.Neutral,
				>= '\u02C9' and <= '\u02CB' => EastAsianWidthType.Ambiguous,
				'\u02CC' => EastAsianWidthType.Neutral,
				'\u02CD' => EastAsianWidthType.Ambiguous,
				>= '\u02CE' and <= '\u02CF' => EastAsianWidthType.Neutral,
				'\u02D0' => EastAsianWidthType.Ambiguous,
				'\u02D1' => EastAsianWidthType.Neutral,
				>= '\u02D2' and <= '\u02D7' => EastAsianWidthType.Neutral,
				>= '\u02D8' and <= '\u02DB' => EastAsianWidthType.Ambiguous,
				'\u02DC' => EastAsianWidthType.Neutral,
				'\u02DD' => EastAsianWidthType.Ambiguous,
				'\u02DE' => EastAsianWidthType.Neutral,
				'\u02DF' => EastAsianWidthType.Ambiguous,
				>= '\u02E0' and <= '\u02E4' => EastAsianWidthType.Neutral,
				>= '\u02E5' and <= '\u02EB' => EastAsianWidthType.Neutral,
				'\u02EC' => EastAsianWidthType.Neutral,
				'\u02ED' => EastAsianWidthType.Neutral,
				'\u02EE' => EastAsianWidthType.Neutral,
				>= '\u02EF' and <= '\u02FF' => EastAsianWidthType.Neutral,
				>= '\u0300' and <= '\u036F' => EastAsianWidthType.Ambiguous,
				>= '\u0370' and <= '\u0373' => EastAsianWidthType.Neutral,
				'\u0374' => EastAsianWidthType.Neutral,
				'\u0375' => EastAsianWidthType.Neutral,
				>= '\u0376' and <= '\u0377' => EastAsianWidthType.Neutral,
				'\u037A' => EastAsianWidthType.Neutral,
				>= '\u037B' and <= '\u037D' => EastAsianWidthType.Neutral,
				'\u037E' => EastAsianWidthType.Neutral,
				'\u037F' => EastAsianWidthType.Neutral,
				>= '\u0384' and <= '\u0385' => EastAsianWidthType.Neutral,
				'\u0386' => EastAsianWidthType.Neutral,
				'\u0387' => EastAsianWidthType.Neutral,
				>= '\u0388' and <= '\u038A' => EastAsianWidthType.Neutral,
				'\u038C' => EastAsianWidthType.Neutral,
				>= '\u038E' and <= '\u0390' => EastAsianWidthType.Neutral,
				>= '\u0391' and <= '\u03A1' => EastAsianWidthType.Ambiguous,
				>= '\u03A3' and <= '\u03A9' => EastAsianWidthType.Ambiguous,
				>= '\u03AA' and <= '\u03B0' => EastAsianWidthType.Neutral,
				>= '\u03B1' and <= '\u03C1' => EastAsianWidthType.Ambiguous,
				'\u03C2' => EastAsianWidthType.Neutral,
				>= '\u03C3' and <= '\u03C9' => EastAsianWidthType.Ambiguous,
				>= '\u03CA' and <= '\u03F5' => EastAsianWidthType.Neutral,
				'\u03F6' => EastAsianWidthType.Neutral,
				>= '\u03F7' and <= '\u03FF' => EastAsianWidthType.Neutral,
				'\u0400' => EastAsianWidthType.Neutral,
				'\u0401' => EastAsianWidthType.Ambiguous,
				>= '\u0402' and <= '\u040F' => EastAsianWidthType.Neutral,
				>= '\u0410' and <= '\u044F' => EastAsianWidthType.Ambiguous,
				'\u0450' => EastAsianWidthType.Neutral,
				'\u0451' => EastAsianWidthType.Ambiguous,
				>= '\u0452' and <= '\u0481' => EastAsianWidthType.Neutral,
				'\u0482' => EastAsianWidthType.Neutral,
				>= '\u0483' and <= '\u0487' => EastAsianWidthType.Neutral,
				>= '\u0488' and <= '\u0489' => EastAsianWidthType.Neutral,
				>= '\u048A' and <= '\u04FF' => EastAsianWidthType.Neutral,
				>= '\u0500' and <= '\u052F' => EastAsianWidthType.Neutral,
				>= '\u0531' and <= '\u0556' => EastAsianWidthType.Neutral,
				'\u0559' => EastAsianWidthType.Neutral,
				>= '\u055A' and <= '\u055F' => EastAsianWidthType.Neutral,
				>= '\u0560' and <= '\u0588' => EastAsianWidthType.Neutral,
				'\u0589' => EastAsianWidthType.Neutral,
				'\u058A' => EastAsianWidthType.Neutral,
				>= '\u058D' and <= '\u058E' => EastAsianWidthType.Neutral,
				'\u058F' => EastAsianWidthType.Neutral,
				>= '\u0591' and <= '\u05BD' => EastAsianWidthType.Neutral,
				'\u05BE' => EastAsianWidthType.Neutral,
				'\u05BF' => EastAsianWidthType.Neutral,
				'\u05C0' => EastAsianWidthType.Neutral,
				>= '\u05C1' and <= '\u05C2' => EastAsianWidthType.Neutral,
				'\u05C3' => EastAsianWidthType.Neutral,
				>= '\u05C4' and <= '\u05C5' => EastAsianWidthType.Neutral,
				'\u05C6' => EastAsianWidthType.Neutral,
				'\u05C7' => EastAsianWidthType.Neutral,
				>= '\u05D0' and <= '\u05EA' => EastAsianWidthType.Neutral,
				>= '\u05EF' and <= '\u05F2' => EastAsianWidthType.Neutral,
				>= '\u05F3' and <= '\u05F4' => EastAsianWidthType.Neutral,
				>= '\u0600' and <= '\u0605' => EastAsianWidthType.Neutral,
				>= '\u0606' and <= '\u0608' => EastAsianWidthType.Neutral,
				>= '\u0609' and <= '\u060A' => EastAsianWidthType.Neutral,
				'\u060B' => EastAsianWidthType.Neutral,
				>= '\u060C' and <= '\u060D' => EastAsianWidthType.Neutral,
				>= '\u060E' and <= '\u060F' => EastAsianWidthType.Neutral,
				>= '\u0610' and <= '\u061A' => EastAsianWidthType.Neutral,
				'\u061B' => EastAsianWidthType.Neutral,
				'\u061C' => EastAsianWidthType.Neutral,
				>= '\u061E' and <= '\u061F' => EastAsianWidthType.Neutral,
				>= '\u0620' and <= '\u063F' => EastAsianWidthType.Neutral,
				'\u0640' => EastAsianWidthType.Neutral,
				>= '\u0641' and <= '\u064A' => EastAsianWidthType.Neutral,
				>= '\u064B' and <= '\u065F' => EastAsianWidthType.Neutral,
				>= '\u0660' and <= '\u0669' => EastAsianWidthType.Neutral,
				>= '\u066A' and <= '\u066D' => EastAsianWidthType.Neutral,
				>= '\u066E' and <= '\u066F' => EastAsianWidthType.Neutral,
				'\u0670' => EastAsianWidthType.Neutral,
				>= '\u0671' and <= '\u06D3' => EastAsianWidthType.Neutral,
				'\u06D4' => EastAsianWidthType.Neutral,
				'\u06D5' => EastAsianWidthType.Neutral,
				>= '\u06D6' and <= '\u06DC' => EastAsianWidthType.Neutral,
				'\u06DD' => EastAsianWidthType.Neutral,
				'\u06DE' => EastAsianWidthType.Neutral,
				>= '\u06DF' and <= '\u06E4' => EastAsianWidthType.Neutral,
				>= '\u06E5' and <= '\u06E6' => EastAsianWidthType.Neutral,
				>= '\u06E7' and <= '\u06E8' => EastAsianWidthType.Neutral,
				'\u06E9' => EastAsianWidthType.Neutral,
				>= '\u06EA' and <= '\u06ED' => EastAsianWidthType.Neutral,
				>= '\u06EE' and <= '\u06EF' => EastAsianWidthType.Neutral,
				>= '\u06F0' and <= '\u06F9' => EastAsianWidthType.Neutral,
				>= '\u06FA' and <= '\u06FC' => EastAsianWidthType.Neutral,
				>= '\u06FD' and <= '\u06FE' => EastAsianWidthType.Neutral,
				'\u06FF' => EastAsianWidthType.Neutral,
				>= '\u0700' and <= '\u070D' => EastAsianWidthType.Neutral,
				'\u070F' => EastAsianWidthType.Neutral,
				'\u0710' => EastAsianWidthType.Neutral,
				'\u0711' => EastAsianWidthType.Neutral,
				>= '\u0712' and <= '\u072F' => EastAsianWidthType.Neutral,
				>= '\u0730' and <= '\u074A' => EastAsianWidthType.Neutral,
				>= '\u074D' and <= '\u074F' => EastAsianWidthType.Neutral,
				>= '\u0750' and <= '\u077F' => EastAsianWidthType.Neutral,
				>= '\u0780' and <= '\u07A5' => EastAsianWidthType.Neutral,
				>= '\u07A6' and <= '\u07B0' => EastAsianWidthType.Neutral,
				'\u07B1' => EastAsianWidthType.Neutral,
				>= '\u07C0' and <= '\u07C9' => EastAsianWidthType.Neutral,
				>= '\u07CA' and <= '\u07EA' => EastAsianWidthType.Neutral,
				>= '\u07EB' and <= '\u07F3' => EastAsianWidthType.Neutral,
				>= '\u07F4' and <= '\u07F5' => EastAsianWidthType.Neutral,
				'\u07F6' => EastAsianWidthType.Neutral,
				>= '\u07F7' and <= '\u07F9' => EastAsianWidthType.Neutral,
				'\u07FA' => EastAsianWidthType.Neutral,
				'\u07FD' => EastAsianWidthType.Neutral,
				>= '\u07FE' and <= '\u07FF' => EastAsianWidthType.Neutral,
				>= '\u0800' and <= '\u0815' => EastAsianWidthType.Neutral,
				>= '\u0816' and <= '\u0819' => EastAsianWidthType.Neutral,
				'\u081A' => EastAsianWidthType.Neutral,
				>= '\u081B' and <= '\u0823' => EastAsianWidthType.Neutral,
				'\u0824' => EastAsianWidthType.Neutral,
				>= '\u0825' and <= '\u0827' => EastAsianWidthType.Neutral,
				'\u0828' => EastAsianWidthType.Neutral,
				>= '\u0829' and <= '\u082D' => EastAsianWidthType.Neutral,
				>= '\u0830' and <= '\u083E' => EastAsianWidthType.Neutral,
				>= '\u0840' and <= '\u0858' => EastAsianWidthType.Neutral,
				>= '\u0859' and <= '\u085B' => EastAsianWidthType.Neutral,
				'\u085E' => EastAsianWidthType.Neutral,
				>= '\u0860' and <= '\u086A' => EastAsianWidthType.Neutral,
				>= '\u08A0' and <= '\u08B4' => EastAsianWidthType.Neutral,
				>= '\u08B6' and <= '\u08BD' => EastAsianWidthType.Neutral,
				>= '\u08D3' and <= '\u08E1' => EastAsianWidthType.Neutral,
				'\u08E2' => EastAsianWidthType.Neutral,
				>= '\u08E3' and <= '\u08FF' => EastAsianWidthType.Neutral,
				>= '\u0900' and <= '\u0902' => EastAsianWidthType.Neutral,
				'\u0903' => EastAsianWidthType.Neutral,
				>= '\u0904' and <= '\u0939' => EastAsianWidthType.Neutral,
				'\u093A' => EastAsianWidthType.Neutral,
				'\u093B' => EastAsianWidthType.Neutral,
				'\u093C' => EastAsianWidthType.Neutral,
				'\u093D' => EastAsianWidthType.Neutral,
				>= '\u093E' and <= '\u0940' => EastAsianWidthType.Neutral,
				>= '\u0941' and <= '\u0948' => EastAsianWidthType.Neutral,
				>= '\u0949' and <= '\u094C' => EastAsianWidthType.Neutral,
				'\u094D' => EastAsianWidthType.Neutral,
				>= '\u094E' and <= '\u094F' => EastAsianWidthType.Neutral,
				'\u0950' => EastAsianWidthType.Neutral,
				>= '\u0951' and <= '\u0957' => EastAsianWidthType.Neutral,
				>= '\u0958' and <= '\u0961' => EastAsianWidthType.Neutral,
				>= '\u0962' and <= '\u0963' => EastAsianWidthType.Neutral,
				>= '\u0964' and <= '\u0965' => EastAsianWidthType.Neutral,
				>= '\u0966' and <= '\u096F' => EastAsianWidthType.Neutral,
				'\u0970' => EastAsianWidthType.Neutral,
				'\u0971' => EastAsianWidthType.Neutral,
				>= '\u0972' and <= '\u097F' => EastAsianWidthType.Neutral,
				'\u0980' => EastAsianWidthType.Neutral,
				'\u0981' => EastAsianWidthType.Neutral,
				>= '\u0982' and <= '\u0983' => EastAsianWidthType.Neutral,
				>= '\u0985' and <= '\u098C' => EastAsianWidthType.Neutral,
				>= '\u098F' and <= '\u0990' => EastAsianWidthType.Neutral,
				>= '\u0993' and <= '\u09A8' => EastAsianWidthType.Neutral,
				>= '\u09AA' and <= '\u09B0' => EastAsianWidthType.Neutral,
				'\u09B2' => EastAsianWidthType.Neutral,
				>= '\u09B6' and <= '\u09B9' => EastAsianWidthType.Neutral,
				'\u09BC' => EastAsianWidthType.Neutral,
				'\u09BD' => EastAsianWidthType.Neutral,
				>= '\u09BE' and <= '\u09C0' => EastAsianWidthType.Neutral,
				>= '\u09C1' and <= '\u09C4' => EastAsianWidthType.Neutral,
				>= '\u09C7' and <= '\u09C8' => EastAsianWidthType.Neutral,
				>= '\u09CB' and <= '\u09CC' => EastAsianWidthType.Neutral,
				'\u09CD' => EastAsianWidthType.Neutral,
				'\u09CE' => EastAsianWidthType.Neutral,
				'\u09D7' => EastAsianWidthType.Neutral,
				>= '\u09DC' and <= '\u09DD' => EastAsianWidthType.Neutral,
				>= '\u09DF' and <= '\u09E1' => EastAsianWidthType.Neutral,
				>= '\u09E2' and <= '\u09E3' => EastAsianWidthType.Neutral,
				>= '\u09E6' and <= '\u09EF' => EastAsianWidthType.Neutral,
				>= '\u09F0' and <= '\u09F1' => EastAsianWidthType.Neutral,
				>= '\u09F2' and <= '\u09F3' => EastAsianWidthType.Neutral,
				>= '\u09F4' and <= '\u09F9' => EastAsianWidthType.Neutral,
				'\u09FA' => EastAsianWidthType.Neutral,
				'\u09FB' => EastAsianWidthType.Neutral,
				'\u09FC' => EastAsianWidthType.Neutral,
				'\u09FD' => EastAsianWidthType.Neutral,
				'\u09FE' => EastAsianWidthType.Neutral,
				>= '\u0A01' and <= '\u0A02' => EastAsianWidthType.Neutral,
				'\u0A03' => EastAsianWidthType.Neutral,
				>= '\u0A05' and <= '\u0A0A' => EastAsianWidthType.Neutral,
				>= '\u0A0F' and <= '\u0A10' => EastAsianWidthType.Neutral,
				>= '\u0A13' and <= '\u0A28' => EastAsianWidthType.Neutral,
				>= '\u0A2A' and <= '\u0A30' => EastAsianWidthType.Neutral,
				>= '\u0A32' and <= '\u0A33' => EastAsianWidthType.Neutral,
				>= '\u0A35' and <= '\u0A36' => EastAsianWidthType.Neutral,
				>= '\u0A38' and <= '\u0A39' => EastAsianWidthType.Neutral,
				'\u0A3C' => EastAsianWidthType.Neutral,
				>= '\u0A3E' and <= '\u0A40' => EastAsianWidthType.Neutral,
				>= '\u0A41' and <= '\u0A42' => EastAsianWidthType.Neutral,
				>= '\u0A47' and <= '\u0A48' => EastAsianWidthType.Neutral,
				>= '\u0A4B' and <= '\u0A4D' => EastAsianWidthType.Neutral,
				'\u0A51' => EastAsianWidthType.Neutral,
				>= '\u0A59' and <= '\u0A5C' => EastAsianWidthType.Neutral,
				'\u0A5E' => EastAsianWidthType.Neutral,
				>= '\u0A66' and <= '\u0A6F' => EastAsianWidthType.Neutral,
				>= '\u0A70' and <= '\u0A71' => EastAsianWidthType.Neutral,
				>= '\u0A72' and <= '\u0A74' => EastAsianWidthType.Neutral,
				'\u0A75' => EastAsianWidthType.Neutral,
				'\u0A76' => EastAsianWidthType.Neutral,
				>= '\u0A81' and <= '\u0A82' => EastAsianWidthType.Neutral,
				'\u0A83' => EastAsianWidthType.Neutral,
				>= '\u0A85' and <= '\u0A8D' => EastAsianWidthType.Neutral,
				>= '\u0A8F' and <= '\u0A91' => EastAsianWidthType.Neutral,
				>= '\u0A93' and <= '\u0AA8' => EastAsianWidthType.Neutral,
				>= '\u0AAA' and <= '\u0AB0' => EastAsianWidthType.Neutral,
				>= '\u0AB2' and <= '\u0AB3' => EastAsianWidthType.Neutral,
				>= '\u0AB5' and <= '\u0AB9' => EastAsianWidthType.Neutral,
				'\u0ABC' => EastAsianWidthType.Neutral,
				'\u0ABD' => EastAsianWidthType.Neutral,
				>= '\u0ABE' and <= '\u0AC0' => EastAsianWidthType.Neutral,
				>= '\u0AC1' and <= '\u0AC5' => EastAsianWidthType.Neutral,
				>= '\u0AC7' and <= '\u0AC8' => EastAsianWidthType.Neutral,
				'\u0AC9' => EastAsianWidthType.Neutral,
				>= '\u0ACB' and <= '\u0ACC' => EastAsianWidthType.Neutral,
				'\u0ACD' => EastAsianWidthType.Neutral,
				'\u0AD0' => EastAsianWidthType.Neutral,
				>= '\u0AE0' and <= '\u0AE1' => EastAsianWidthType.Neutral,
				>= '\u0AE2' and <= '\u0AE3' => EastAsianWidthType.Neutral,
				>= '\u0AE6' and <= '\u0AEF' => EastAsianWidthType.Neutral,
				'\u0AF0' => EastAsianWidthType.Neutral,
				'\u0AF1' => EastAsianWidthType.Neutral,
				'\u0AF9' => EastAsianWidthType.Neutral,
				>= '\u0AFA' and <= '\u0AFF' => EastAsianWidthType.Neutral,
				'\u0B01' => EastAsianWidthType.Neutral,
				>= '\u0B02' and <= '\u0B03' => EastAsianWidthType.Neutral,
				>= '\u0B05' and <= '\u0B0C' => EastAsianWidthType.Neutral,
				>= '\u0B0F' and <= '\u0B10' => EastAsianWidthType.Neutral,
				>= '\u0B13' and <= '\u0B28' => EastAsianWidthType.Neutral,
				>= '\u0B2A' and <= '\u0B30' => EastAsianWidthType.Neutral,
				>= '\u0B32' and <= '\u0B33' => EastAsianWidthType.Neutral,
				>= '\u0B35' and <= '\u0B39' => EastAsianWidthType.Neutral,
				'\u0B3C' => EastAsianWidthType.Neutral,
				'\u0B3D' => EastAsianWidthType.Neutral,
				'\u0B3E' => EastAsianWidthType.Neutral,
				'\u0B3F' => EastAsianWidthType.Neutral,
				'\u0B40' => EastAsianWidthType.Neutral,
				>= '\u0B41' and <= '\u0B44' => EastAsianWidthType.Neutral,
				>= '\u0B47' and <= '\u0B48' => EastAsianWidthType.Neutral,
				>= '\u0B4B' and <= '\u0B4C' => EastAsianWidthType.Neutral,
				'\u0B4D' => EastAsianWidthType.Neutral,
				'\u0B56' => EastAsianWidthType.Neutral,
				'\u0B57' => EastAsianWidthType.Neutral,
				>= '\u0B5C' and <= '\u0B5D' => EastAsianWidthType.Neutral,
				>= '\u0B5F' and <= '\u0B61' => EastAsianWidthType.Neutral,
				>= '\u0B62' and <= '\u0B63' => EastAsianWidthType.Neutral,
				>= '\u0B66' and <= '\u0B6F' => EastAsianWidthType.Neutral,
				'\u0B70' => EastAsianWidthType.Neutral,
				'\u0B71' => EastAsianWidthType.Neutral,
				>= '\u0B72' and <= '\u0B77' => EastAsianWidthType.Neutral,
				'\u0B82' => EastAsianWidthType.Neutral,
				'\u0B83' => EastAsianWidthType.Neutral,
				>= '\u0B85' and <= '\u0B8A' => EastAsianWidthType.Neutral,
				>= '\u0B8E' and <= '\u0B90' => EastAsianWidthType.Neutral,
				>= '\u0B92' and <= '\u0B95' => EastAsianWidthType.Neutral,
				>= '\u0B99' and <= '\u0B9A' => EastAsianWidthType.Neutral,
				'\u0B9C' => EastAsianWidthType.Neutral,
				>= '\u0B9E' and <= '\u0B9F' => EastAsianWidthType.Neutral,
				>= '\u0BA3' and <= '\u0BA4' => EastAsianWidthType.Neutral,
				>= '\u0BA8' and <= '\u0BAA' => EastAsianWidthType.Neutral,
				>= '\u0BAE' and <= '\u0BB9' => EastAsianWidthType.Neutral,
				>= '\u0BBE' and <= '\u0BBF' => EastAsianWidthType.Neutral,
				'\u0BC0' => EastAsianWidthType.Neutral,
				>= '\u0BC1' and <= '\u0BC2' => EastAsianWidthType.Neutral,
				>= '\u0BC6' and <= '\u0BC8' => EastAsianWidthType.Neutral,
				>= '\u0BCA' and <= '\u0BCC' => EastAsianWidthType.Neutral,
				'\u0BCD' => EastAsianWidthType.Neutral,
				'\u0BD0' => EastAsianWidthType.Neutral,
				'\u0BD7' => EastAsianWidthType.Neutral,
				>= '\u0BE6' and <= '\u0BEF' => EastAsianWidthType.Neutral,
				>= '\u0BF0' and <= '\u0BF2' => EastAsianWidthType.Neutral,
				>= '\u0BF3' and <= '\u0BF8' => EastAsianWidthType.Neutral,
				'\u0BF9' => EastAsianWidthType.Neutral,
				'\u0BFA' => EastAsianWidthType.Neutral,
				'\u0C00' => EastAsianWidthType.Neutral,
				>= '\u0C01' and <= '\u0C03' => EastAsianWidthType.Neutral,
				'\u0C04' => EastAsianWidthType.Neutral,
				>= '\u0C05' and <= '\u0C0C' => EastAsianWidthType.Neutral,
				>= '\u0C0E' and <= '\u0C10' => EastAsianWidthType.Neutral,
				>= '\u0C12' and <= '\u0C28' => EastAsianWidthType.Neutral,
				>= '\u0C2A' and <= '\u0C39' => EastAsianWidthType.Neutral,
				'\u0C3D' => EastAsianWidthType.Neutral,
				>= '\u0C3E' and <= '\u0C40' => EastAsianWidthType.Neutral,
				>= '\u0C41' and <= '\u0C44' => EastAsianWidthType.Neutral,
				>= '\u0C46' and <= '\u0C48' => EastAsianWidthType.Neutral,
				>= '\u0C4A' and <= '\u0C4D' => EastAsianWidthType.Neutral,
				>= '\u0C55' and <= '\u0C56' => EastAsianWidthType.Neutral,
				>= '\u0C58' and <= '\u0C5A' => EastAsianWidthType.Neutral,
				>= '\u0C60' and <= '\u0C61' => EastAsianWidthType.Neutral,
				>= '\u0C62' and <= '\u0C63' => EastAsianWidthType.Neutral,
				>= '\u0C66' and <= '\u0C6F' => EastAsianWidthType.Neutral,
				'\u0C77' => EastAsianWidthType.Neutral,
				>= '\u0C78' and <= '\u0C7E' => EastAsianWidthType.Neutral,
				'\u0C7F' => EastAsianWidthType.Neutral,
				'\u0C80' => EastAsianWidthType.Neutral,
				'\u0C81' => EastAsianWidthType.Neutral,
				>= '\u0C82' and <= '\u0C83' => EastAsianWidthType.Neutral,
				'\u0C84' => EastAsianWidthType.Neutral,
				>= '\u0C85' and <= '\u0C8C' => EastAsianWidthType.Neutral,
				>= '\u0C8E' and <= '\u0C90' => EastAsianWidthType.Neutral,
				>= '\u0C92' and <= '\u0CA8' => EastAsianWidthType.Neutral,
				>= '\u0CAA' and <= '\u0CB3' => EastAsianWidthType.Neutral,
				>= '\u0CB5' and <= '\u0CB9' => EastAsianWidthType.Neutral,
				'\u0CBC' => EastAsianWidthType.Neutral,
				'\u0CBD' => EastAsianWidthType.Neutral,
				'\u0CBE' => EastAsianWidthType.Neutral,
				'\u0CBF' => EastAsianWidthType.Neutral,
				>= '\u0CC0' and <= '\u0CC4' => EastAsianWidthType.Neutral,
				'\u0CC6' => EastAsianWidthType.Neutral,
				>= '\u0CC7' and <= '\u0CC8' => EastAsianWidthType.Neutral,
				>= '\u0CCA' and <= '\u0CCB' => EastAsianWidthType.Neutral,
				>= '\u0CCC' and <= '\u0CCD' => EastAsianWidthType.Neutral,
				>= '\u0CD5' and <= '\u0CD6' => EastAsianWidthType.Neutral,
				'\u0CDE' => EastAsianWidthType.Neutral,
				>= '\u0CE0' and <= '\u0CE1' => EastAsianWidthType.Neutral,
				>= '\u0CE2' and <= '\u0CE3' => EastAsianWidthType.Neutral,
				>= '\u0CE6' and <= '\u0CEF' => EastAsianWidthType.Neutral,
				>= '\u0CF1' and <= '\u0CF2' => EastAsianWidthType.Neutral,
				>= '\u0D00' and <= '\u0D01' => EastAsianWidthType.Neutral,
				>= '\u0D02' and <= '\u0D03' => EastAsianWidthType.Neutral,
				>= '\u0D05' and <= '\u0D0C' => EastAsianWidthType.Neutral,
				>= '\u0D0E' and <= '\u0D10' => EastAsianWidthType.Neutral,
				>= '\u0D12' and <= '\u0D3A' => EastAsianWidthType.Neutral,
				>= '\u0D3B' and <= '\u0D3C' => EastAsianWidthType.Neutral,
				'\u0D3D' => EastAsianWidthType.Neutral,
				>= '\u0D3E' and <= '\u0D40' => EastAsianWidthType.Neutral,
				>= '\u0D41' and <= '\u0D44' => EastAsianWidthType.Neutral,
				>= '\u0D46' and <= '\u0D48' => EastAsianWidthType.Neutral,
				>= '\u0D4A' and <= '\u0D4C' => EastAsianWidthType.Neutral,
				'\u0D4D' => EastAsianWidthType.Neutral,
				'\u0D4E' => EastAsianWidthType.Neutral,
				'\u0D4F' => EastAsianWidthType.Neutral,
				>= '\u0D54' and <= '\u0D56' => EastAsianWidthType.Neutral,
				'\u0D57' => EastAsianWidthType.Neutral,
				>= '\u0D58' and <= '\u0D5E' => EastAsianWidthType.Neutral,
				>= '\u0D5F' and <= '\u0D61' => EastAsianWidthType.Neutral,
				>= '\u0D62' and <= '\u0D63' => EastAsianWidthType.Neutral,
				>= '\u0D66' and <= '\u0D6F' => EastAsianWidthType.Neutral,
				>= '\u0D70' and <= '\u0D78' => EastAsianWidthType.Neutral,
				'\u0D79' => EastAsianWidthType.Neutral,
				>= '\u0D7A' and <= '\u0D7F' => EastAsianWidthType.Neutral,
				>= '\u0D82' and <= '\u0D83' => EastAsianWidthType.Neutral,
				>= '\u0D85' and <= '\u0D96' => EastAsianWidthType.Neutral,
				>= '\u0D9A' and <= '\u0DB1' => EastAsianWidthType.Neutral,
				>= '\u0DB3' and <= '\u0DBB' => EastAsianWidthType.Neutral,
				'\u0DBD' => EastAsianWidthType.Neutral,
				>= '\u0DC0' and <= '\u0DC6' => EastAsianWidthType.Neutral,
				'\u0DCA' => EastAsianWidthType.Neutral,
				>= '\u0DCF' and <= '\u0DD1' => EastAsianWidthType.Neutral,
				>= '\u0DD2' and <= '\u0DD4' => EastAsianWidthType.Neutral,
				'\u0DD6' => EastAsianWidthType.Neutral,
				>= '\u0DD8' and <= '\u0DDF' => EastAsianWidthType.Neutral,
				>= '\u0DE6' and <= '\u0DEF' => EastAsianWidthType.Neutral,
				>= '\u0DF2' and <= '\u0DF3' => EastAsianWidthType.Neutral,
				'\u0DF4' => EastAsianWidthType.Neutral,
				>= '\u0E01' and <= '\u0E30' => EastAsianWidthType.Neutral,
				'\u0E31' => EastAsianWidthType.Neutral,
				>= '\u0E32' and <= '\u0E33' => EastAsianWidthType.Neutral,
				>= '\u0E34' and <= '\u0E3A' => EastAsianWidthType.Neutral,
				'\u0E3F' => EastAsianWidthType.Neutral,
				>= '\u0E40' and <= '\u0E45' => EastAsianWidthType.Neutral,
				'\u0E46' => EastAsianWidthType.Neutral,
				>= '\u0E47' and <= '\u0E4E' => EastAsianWidthType.Neutral,
				'\u0E4F' => EastAsianWidthType.Neutral,
				>= '\u0E50' and <= '\u0E59' => EastAsianWidthType.Neutral,
				>= '\u0E5A' and <= '\u0E5B' => EastAsianWidthType.Neutral,
				>= '\u0E81' and <= '\u0E82' => EastAsianWidthType.Neutral,
				'\u0E84' => EastAsianWidthType.Neutral,
				>= '\u0E86' and <= '\u0E8A' => EastAsianWidthType.Neutral,
				>= '\u0E8C' and <= '\u0EA3' => EastAsianWidthType.Neutral,
				'\u0EA5' => EastAsianWidthType.Neutral,
				>= '\u0EA7' and <= '\u0EB0' => EastAsianWidthType.Neutral,
				'\u0EB1' => EastAsianWidthType.Neutral,
				>= '\u0EB2' and <= '\u0EB3' => EastAsianWidthType.Neutral,
				>= '\u0EB4' and <= '\u0EBC' => EastAsianWidthType.Neutral,
				'\u0EBD' => EastAsianWidthType.Neutral,
				>= '\u0EC0' and <= '\u0EC4' => EastAsianWidthType.Neutral,
				'\u0EC6' => EastAsianWidthType.Neutral,
				>= '\u0EC8' and <= '\u0ECD' => EastAsianWidthType.Neutral,
				>= '\u0ED0' and <= '\u0ED9' => EastAsianWidthType.Neutral,
				>= '\u0EDC' and <= '\u0EDF' => EastAsianWidthType.Neutral,
				'\u0F00' => EastAsianWidthType.Neutral,
				>= '\u0F01' and <= '\u0F03' => EastAsianWidthType.Neutral,
				>= '\u0F04' and <= '\u0F12' => EastAsianWidthType.Neutral,
				'\u0F13' => EastAsianWidthType.Neutral,
				'\u0F14' => EastAsianWidthType.Neutral,
				>= '\u0F15' and <= '\u0F17' => EastAsianWidthType.Neutral,
				>= '\u0F18' and <= '\u0F19' => EastAsianWidthType.Neutral,
				>= '\u0F1A' and <= '\u0F1F' => EastAsianWidthType.Neutral,
				>= '\u0F20' and <= '\u0F29' => EastAsianWidthType.Neutral,
				>= '\u0F2A' and <= '\u0F33' => EastAsianWidthType.Neutral,
				'\u0F34' => EastAsianWidthType.Neutral,
				'\u0F35' => EastAsianWidthType.Neutral,
				'\u0F36' => EastAsianWidthType.Neutral,
				'\u0F37' => EastAsianWidthType.Neutral,
				'\u0F38' => EastAsianWidthType.Neutral,
				'\u0F39' => EastAsianWidthType.Neutral,
				'\u0F3A' => EastAsianWidthType.Neutral,
				'\u0F3B' => EastAsianWidthType.Neutral,
				'\u0F3C' => EastAsianWidthType.Neutral,
				'\u0F3D' => EastAsianWidthType.Neutral,
				>= '\u0F3E' and <= '\u0F3F' => EastAsianWidthType.Neutral,
				>= '\u0F40' and <= '\u0F47' => EastAsianWidthType.Neutral,
				>= '\u0F49' and <= '\u0F6C' => EastAsianWidthType.Neutral,
				>= '\u0F71' and <= '\u0F7E' => EastAsianWidthType.Neutral,
				'\u0F7F' => EastAsianWidthType.Neutral,
				>= '\u0F80' and <= '\u0F84' => EastAsianWidthType.Neutral,
				'\u0F85' => EastAsianWidthType.Neutral,
				>= '\u0F86' and <= '\u0F87' => EastAsianWidthType.Neutral,
				>= '\u0F88' and <= '\u0F8C' => EastAsianWidthType.Neutral,
				>= '\u0F8D' and <= '\u0F97' => EastAsianWidthType.Neutral,
				>= '\u0F99' and <= '\u0FBC' => EastAsianWidthType.Neutral,
				>= '\u0FBE' and <= '\u0FC5' => EastAsianWidthType.Neutral,
				'\u0FC6' => EastAsianWidthType.Neutral,
				>= '\u0FC7' and <= '\u0FCC' => EastAsianWidthType.Neutral,
				>= '\u0FCE' and <= '\u0FCF' => EastAsianWidthType.Neutral,
				>= '\u0FD0' and <= '\u0FD4' => EastAsianWidthType.Neutral,
				>= '\u0FD5' and <= '\u0FD8' => EastAsianWidthType.Neutral,
				>= '\u0FD9' and <= '\u0FDA' => EastAsianWidthType.Neutral,
				>= '\u1000' and <= '\u102A' => EastAsianWidthType.Neutral,
				>= '\u102B' and <= '\u102C' => EastAsianWidthType.Neutral,
				>= '\u102D' and <= '\u1030' => EastAsianWidthType.Neutral,
				'\u1031' => EastAsianWidthType.Neutral,
				>= '\u1032' and <= '\u1037' => EastAsianWidthType.Neutral,
				'\u1038' => EastAsianWidthType.Neutral,
				>= '\u1039' and <= '\u103A' => EastAsianWidthType.Neutral,
				>= '\u103B' and <= '\u103C' => EastAsianWidthType.Neutral,
				>= '\u103D' and <= '\u103E' => EastAsianWidthType.Neutral,
				'\u103F' => EastAsianWidthType.Neutral,
				>= '\u1040' and <= '\u1049' => EastAsianWidthType.Neutral,
				>= '\u104A' and <= '\u104F' => EastAsianWidthType.Neutral,
				>= '\u1050' and <= '\u1055' => EastAsianWidthType.Neutral,
				>= '\u1056' and <= '\u1057' => EastAsianWidthType.Neutral,
				>= '\u1058' and <= '\u1059' => EastAsianWidthType.Neutral,
				>= '\u105A' and <= '\u105D' => EastAsianWidthType.Neutral,
				>= '\u105E' and <= '\u1060' => EastAsianWidthType.Neutral,
				'\u1061' => EastAsianWidthType.Neutral,
				>= '\u1062' and <= '\u1064' => EastAsianWidthType.Neutral,
				>= '\u1065' and <= '\u1066' => EastAsianWidthType.Neutral,
				>= '\u1067' and <= '\u106D' => EastAsianWidthType.Neutral,
				>= '\u106E' and <= '\u1070' => EastAsianWidthType.Neutral,
				>= '\u1071' and <= '\u1074' => EastAsianWidthType.Neutral,
				>= '\u1075' and <= '\u1081' => EastAsianWidthType.Neutral,
				'\u1082' => EastAsianWidthType.Neutral,
				>= '\u1083' and <= '\u1084' => EastAsianWidthType.Neutral,
				>= '\u1085' and <= '\u1086' => EastAsianWidthType.Neutral,
				>= '\u1087' and <= '\u108C' => EastAsianWidthType.Neutral,
				'\u108D' => EastAsianWidthType.Neutral,
				'\u108E' => EastAsianWidthType.Neutral,
				'\u108F' => EastAsianWidthType.Neutral,
				>= '\u1090' and <= '\u1099' => EastAsianWidthType.Neutral,
				>= '\u109A' and <= '\u109C' => EastAsianWidthType.Neutral,
				'\u109D' => EastAsianWidthType.Neutral,
				>= '\u109E' and <= '\u109F' => EastAsianWidthType.Neutral,
				>= '\u10A0' and <= '\u10C5' => EastAsianWidthType.Neutral,
				'\u10C7' => EastAsianWidthType.Neutral,
				'\u10CD' => EastAsianWidthType.Neutral,
				>= '\u10D0' and <= '\u10FA' => EastAsianWidthType.Neutral,
				'\u10FB' => EastAsianWidthType.Neutral,
				'\u10FC' => EastAsianWidthType.Neutral,
				>= '\u10FD' and <= '\u10FF' => EastAsianWidthType.Neutral,
				>= '\u1100' and <= '\u115F' => EastAsianWidthType.Wide,
				>= '\u1160' and <= '\u11FF' => EastAsianWidthType.Neutral,
				>= '\u1200' and <= '\u1248' => EastAsianWidthType.Neutral,
				>= '\u124A' and <= '\u124D' => EastAsianWidthType.Neutral,
				>= '\u1250' and <= '\u1256' => EastAsianWidthType.Neutral,
				'\u1258' => EastAsianWidthType.Neutral,
				>= '\u125A' and <= '\u125D' => EastAsianWidthType.Neutral,
				>= '\u1260' and <= '\u1288' => EastAsianWidthType.Neutral,
				>= '\u128A' and <= '\u128D' => EastAsianWidthType.Neutral,
				>= '\u1290' and <= '\u12B0' => EastAsianWidthType.Neutral,
				>= '\u12B2' and <= '\u12B5' => EastAsianWidthType.Neutral,
				>= '\u12B8' and <= '\u12BE' => EastAsianWidthType.Neutral,
				'\u12C0' => EastAsianWidthType.Neutral,
				>= '\u12C2' and <= '\u12C5' => EastAsianWidthType.Neutral,
				>= '\u12C8' and <= '\u12D6' => EastAsianWidthType.Neutral,
				>= '\u12D8' and <= '\u1310' => EastAsianWidthType.Neutral,
				>= '\u1312' and <= '\u1315' => EastAsianWidthType.Neutral,
				>= '\u1318' and <= '\u135A' => EastAsianWidthType.Neutral,
				>= '\u135D' and <= '\u135F' => EastAsianWidthType.Neutral,
				>= '\u1360' and <= '\u1368' => EastAsianWidthType.Neutral,
				>= '\u1369' and <= '\u137C' => EastAsianWidthType.Neutral,
				>= '\u1380' and <= '\u138F' => EastAsianWidthType.Neutral,
				>= '\u1390' and <= '\u1399' => EastAsianWidthType.Neutral,
				>= '\u13A0' and <= '\u13F5' => EastAsianWidthType.Neutral,
				>= '\u13F8' and <= '\u13FD' => EastAsianWidthType.Neutral,
				'\u1400' => EastAsianWidthType.Neutral,
				>= '\u1401' and <= '\u166C' => EastAsianWidthType.Neutral,
				'\u166D' => EastAsianWidthType.Neutral,
				'\u166E' => EastAsianWidthType.Neutral,
				>= '\u166F' and <= '\u167F' => EastAsianWidthType.Neutral,
				'\u1680' => EastAsianWidthType.Neutral,
				>= '\u1681' and <= '\u169A' => EastAsianWidthType.Neutral,
				'\u169B' => EastAsianWidthType.Neutral,
				'\u169C' => EastAsianWidthType.Neutral,
				>= '\u16A0' and <= '\u16EA' => EastAsianWidthType.Neutral,
				>= '\u16EB' and <= '\u16ED' => EastAsianWidthType.Neutral,
				>= '\u16EE' and <= '\u16F0' => EastAsianWidthType.Neutral,
				>= '\u16F1' and <= '\u16F8' => EastAsianWidthType.Neutral,
				>= '\u1700' and <= '\u170C' => EastAsianWidthType.Neutral,
				>= '\u170E' and <= '\u1711' => EastAsianWidthType.Neutral,
				>= '\u1712' and <= '\u1714' => EastAsianWidthType.Neutral,
				>= '\u1720' and <= '\u1731' => EastAsianWidthType.Neutral,
				>= '\u1732' and <= '\u1734' => EastAsianWidthType.Neutral,
				>= '\u1735' and <= '\u1736' => EastAsianWidthType.Neutral,
				>= '\u1740' and <= '\u1751' => EastAsianWidthType.Neutral,
				>= '\u1752' and <= '\u1753' => EastAsianWidthType.Neutral,
				>= '\u1760' and <= '\u176C' => EastAsianWidthType.Neutral,
				>= '\u176E' and <= '\u1770' => EastAsianWidthType.Neutral,
				>= '\u1772' and <= '\u1773' => EastAsianWidthType.Neutral,
				>= '\u1780' and <= '\u17B3' => EastAsianWidthType.Neutral,
				>= '\u17B4' and <= '\u17B5' => EastAsianWidthType.Neutral,
				'\u17B6' => EastAsianWidthType.Neutral,
				>= '\u17B7' and <= '\u17BD' => EastAsianWidthType.Neutral,
				>= '\u17BE' and <= '\u17C5' => EastAsianWidthType.Neutral,
				'\u17C6' => EastAsianWidthType.Neutral,
				>= '\u17C7' and <= '\u17C8' => EastAsianWidthType.Neutral,
				>= '\u17C9' and <= '\u17D3' => EastAsianWidthType.Neutral,
				>= '\u17D4' and <= '\u17D6' => EastAsianWidthType.Neutral,
				'\u17D7' => EastAsianWidthType.Neutral,
				>= '\u17D8' and <= '\u17DA' => EastAsianWidthType.Neutral,
				'\u17DB' => EastAsianWidthType.Neutral,
				'\u17DC' => EastAsianWidthType.Neutral,
				'\u17DD' => EastAsianWidthType.Neutral,
				>= '\u17E0' and <= '\u17E9' => EastAsianWidthType.Neutral,
				>= '\u17F0' and <= '\u17F9' => EastAsianWidthType.Neutral,
				>= '\u1800' and <= '\u1805' => EastAsianWidthType.Neutral,
				'\u1806' => EastAsianWidthType.Neutral,
				>= '\u1807' and <= '\u180A' => EastAsianWidthType.Neutral,
				>= '\u180B' and <= '\u180D' => EastAsianWidthType.Neutral,
				'\u180E' => EastAsianWidthType.Neutral,
				>= '\u1810' and <= '\u1819' => EastAsianWidthType.Neutral,
				>= '\u1820' and <= '\u1842' => EastAsianWidthType.Neutral,
				'\u1843' => EastAsianWidthType.Neutral,
				>= '\u1844' and <= '\u1878' => EastAsianWidthType.Neutral,
				>= '\u1880' and <= '\u1884' => EastAsianWidthType.Neutral,
				>= '\u1885' and <= '\u1886' => EastAsianWidthType.Neutral,
				>= '\u1887' and <= '\u18A8' => EastAsianWidthType.Neutral,
				'\u18A9' => EastAsianWidthType.Neutral,
				'\u18AA' => EastAsianWidthType.Neutral,
				>= '\u18B0' and <= '\u18F5' => EastAsianWidthType.Neutral,
				>= '\u1900' and <= '\u191E' => EastAsianWidthType.Neutral,
				>= '\u1920' and <= '\u1922' => EastAsianWidthType.Neutral,
				>= '\u1923' and <= '\u1926' => EastAsianWidthType.Neutral,
				>= '\u1927' and <= '\u1928' => EastAsianWidthType.Neutral,
				>= '\u1929' and <= '\u192B' => EastAsianWidthType.Neutral,
				>= '\u1930' and <= '\u1931' => EastAsianWidthType.Neutral,
				'\u1932' => EastAsianWidthType.Neutral,
				>= '\u1933' and <= '\u1938' => EastAsianWidthType.Neutral,
				>= '\u1939' and <= '\u193B' => EastAsianWidthType.Neutral,
				'\u1940' => EastAsianWidthType.Neutral,
				>= '\u1944' and <= '\u1945' => EastAsianWidthType.Neutral,
				>= '\u1946' and <= '\u194F' => EastAsianWidthType.Neutral,
				>= '\u1950' and <= '\u196D' => EastAsianWidthType.Neutral,
				>= '\u1970' and <= '\u1974' => EastAsianWidthType.Neutral,
				>= '\u1980' and <= '\u19AB' => EastAsianWidthType.Neutral,
				>= '\u19B0' and <= '\u19C9' => EastAsianWidthType.Neutral,
				>= '\u19D0' and <= '\u19D9' => EastAsianWidthType.Neutral,
				'\u19DA' => EastAsianWidthType.Neutral,
				>= '\u19DE' and <= '\u19DF' => EastAsianWidthType.Neutral,
				>= '\u19E0' and <= '\u19FF' => EastAsianWidthType.Neutral,
				>= '\u1A00' and <= '\u1A16' => EastAsianWidthType.Neutral,
				>= '\u1A17' and <= '\u1A18' => EastAsianWidthType.Neutral,
				>= '\u1A19' and <= '\u1A1A' => EastAsianWidthType.Neutral,
				'\u1A1B' => EastAsianWidthType.Neutral,
				>= '\u1A1E' and <= '\u1A1F' => EastAsianWidthType.Neutral,
				>= '\u1A20' and <= '\u1A54' => EastAsianWidthType.Neutral,
				'\u1A55' => EastAsianWidthType.Neutral,
				'\u1A56' => EastAsianWidthType.Neutral,
				'\u1A57' => EastAsianWidthType.Neutral,
				>= '\u1A58' and <= '\u1A5E' => EastAsianWidthType.Neutral,
				'\u1A60' => EastAsianWidthType.Neutral,
				'\u1A61' => EastAsianWidthType.Neutral,
				'\u1A62' => EastAsianWidthType.Neutral,
				>= '\u1A63' and <= '\u1A64' => EastAsianWidthType.Neutral,
				>= '\u1A65' and <= '\u1A6C' => EastAsianWidthType.Neutral,
				>= '\u1A6D' and <= '\u1A72' => EastAsianWidthType.Neutral,
				>= '\u1A73' and <= '\u1A7C' => EastAsianWidthType.Neutral,
				'\u1A7F' => EastAsianWidthType.Neutral,
				>= '\u1A80' and <= '\u1A89' => EastAsianWidthType.Neutral,
				>= '\u1A90' and <= '\u1A99' => EastAsianWidthType.Neutral,
				>= '\u1AA0' and <= '\u1AA6' => EastAsianWidthType.Neutral,
				'\u1AA7' => EastAsianWidthType.Neutral,
				>= '\u1AA8' and <= '\u1AAD' => EastAsianWidthType.Neutral,
				>= '\u1AB0' and <= '\u1ABD' => EastAsianWidthType.Neutral,
				'\u1ABE' => EastAsianWidthType.Neutral,
				>= '\u1B00' and <= '\u1B03' => EastAsianWidthType.Neutral,
				'\u1B04' => EastAsianWidthType.Neutral,
				>= '\u1B05' and <= '\u1B33' => EastAsianWidthType.Neutral,
				'\u1B34' => EastAsianWidthType.Neutral,
				'\u1B35' => EastAsianWidthType.Neutral,
				>= '\u1B36' and <= '\u1B3A' => EastAsianWidthType.Neutral,
				'\u1B3B' => EastAsianWidthType.Neutral,
				'\u1B3C' => EastAsianWidthType.Neutral,
				>= '\u1B3D' and <= '\u1B41' => EastAsianWidthType.Neutral,
				'\u1B42' => EastAsianWidthType.Neutral,
				>= '\u1B43' and <= '\u1B44' => EastAsianWidthType.Neutral,
				>= '\u1B45' and <= '\u1B4B' => EastAsianWidthType.Neutral,
				>= '\u1B50' and <= '\u1B59' => EastAsianWidthType.Neutral,
				>= '\u1B5A' and <= '\u1B60' => EastAsianWidthType.Neutral,
				>= '\u1B61' and <= '\u1B6A' => EastAsianWidthType.Neutral,
				>= '\u1B6B' and <= '\u1B73' => EastAsianWidthType.Neutral,
				>= '\u1B74' and <= '\u1B7C' => EastAsianWidthType.Neutral,
				>= '\u1B80' and <= '\u1B81' => EastAsianWidthType.Neutral,
				'\u1B82' => EastAsianWidthType.Neutral,
				>= '\u1B83' and <= '\u1BA0' => EastAsianWidthType.Neutral,
				'\u1BA1' => EastAsianWidthType.Neutral,
				>= '\u1BA2' and <= '\u1BA5' => EastAsianWidthType.Neutral,
				>= '\u1BA6' and <= '\u1BA7' => EastAsianWidthType.Neutral,
				>= '\u1BA8' and <= '\u1BA9' => EastAsianWidthType.Neutral,
				'\u1BAA' => EastAsianWidthType.Neutral,
				>= '\u1BAB' and <= '\u1BAD' => EastAsianWidthType.Neutral,
				>= '\u1BAE' and <= '\u1BAF' => EastAsianWidthType.Neutral,
				>= '\u1BB0' and <= '\u1BB9' => EastAsianWidthType.Neutral,
				>= '\u1BBA' and <= '\u1BBF' => EastAsianWidthType.Neutral,
				>= '\u1BC0' and <= '\u1BE5' => EastAsianWidthType.Neutral,
				'\u1BE6' => EastAsianWidthType.Neutral,
				'\u1BE7' => EastAsianWidthType.Neutral,
				>= '\u1BE8' and <= '\u1BE9' => EastAsianWidthType.Neutral,
				>= '\u1BEA' and <= '\u1BEC' => EastAsianWidthType.Neutral,
				'\u1BED' => EastAsianWidthType.Neutral,
				'\u1BEE' => EastAsianWidthType.Neutral,
				>= '\u1BEF' and <= '\u1BF1' => EastAsianWidthType.Neutral,
				>= '\u1BF2' and <= '\u1BF3' => EastAsianWidthType.Neutral,
				>= '\u1BFC' and <= '\u1BFF' => EastAsianWidthType.Neutral,
				>= '\u1C00' and <= '\u1C23' => EastAsianWidthType.Neutral,
				>= '\u1C24' and <= '\u1C2B' => EastAsianWidthType.Neutral,
				>= '\u1C2C' and <= '\u1C33' => EastAsianWidthType.Neutral,
				>= '\u1C34' and <= '\u1C35' => EastAsianWidthType.Neutral,
				>= '\u1C36' and <= '\u1C37' => EastAsianWidthType.Neutral,
				>= '\u1C3B' and <= '\u1C3F' => EastAsianWidthType.Neutral,
				>= '\u1C40' and <= '\u1C49' => EastAsianWidthType.Neutral,
				>= '\u1C4D' and <= '\u1C4F' => EastAsianWidthType.Neutral,
				>= '\u1C50' and <= '\u1C59' => EastAsianWidthType.Neutral,
				>= '\u1C5A' and <= '\u1C77' => EastAsianWidthType.Neutral,
				>= '\u1C78' and <= '\u1C7D' => EastAsianWidthType.Neutral,
				>= '\u1C7E' and <= '\u1C7F' => EastAsianWidthType.Neutral,
				>= '\u1C80' and <= '\u1C88' => EastAsianWidthType.Neutral,
				>= '\u1C90' and <= '\u1CBA' => EastAsianWidthType.Neutral,
				>= '\u1CBD' and <= '\u1CBF' => EastAsianWidthType.Neutral,
				>= '\u1CC0' and <= '\u1CC7' => EastAsianWidthType.Neutral,
				>= '\u1CD0' and <= '\u1CD2' => EastAsianWidthType.Neutral,
				'\u1CD3' => EastAsianWidthType.Neutral,
				>= '\u1CD4' and <= '\u1CE0' => EastAsianWidthType.Neutral,
				'\u1CE1' => EastAsianWidthType.Neutral,
				>= '\u1CE2' and <= '\u1CE8' => EastAsianWidthType.Neutral,
				>= '\u1CE9' and <= '\u1CEC' => EastAsianWidthType.Neutral,
				'\u1CED' => EastAsianWidthType.Neutral,
				>= '\u1CEE' and <= '\u1CF3' => EastAsianWidthType.Neutral,
				'\u1CF4' => EastAsianWidthType.Neutral,
				>= '\u1CF5' and <= '\u1CF6' => EastAsianWidthType.Neutral,
				'\u1CF7' => EastAsianWidthType.Neutral,
				>= '\u1CF8' and <= '\u1CF9' => EastAsianWidthType.Neutral,
				'\u1CFA' => EastAsianWidthType.Neutral,
				>= '\u1D00' and <= '\u1D2B' => EastAsianWidthType.Neutral,
				>= '\u1D2C' and <= '\u1D6A' => EastAsianWidthType.Neutral,
				>= '\u1D6B' and <= '\u1D77' => EastAsianWidthType.Neutral,
				'\u1D78' => EastAsianWidthType.Neutral,
				>= '\u1D79' and <= '\u1D7F' => EastAsianWidthType.Neutral,
				>= '\u1D80' and <= '\u1D9A' => EastAsianWidthType.Neutral,
				>= '\u1D9B' and <= '\u1DBF' => EastAsianWidthType.Neutral,
				>= '\u1DC0' and <= '\u1DF9' => EastAsianWidthType.Neutral,
				>= '\u1DFB' and <= '\u1DFF' => EastAsianWidthType.Neutral,
				>= '\u1E00' and <= '\u1EFF' => EastAsianWidthType.Neutral,
				>= '\u1F00' and <= '\u1F15' => EastAsianWidthType.Neutral,
				>= '\u1F18' and <= '\u1F1D' => EastAsianWidthType.Neutral,
				>= '\u1F20' and <= '\u1F45' => EastAsianWidthType.Neutral,
				>= '\u1F48' and <= '\u1F4D' => EastAsianWidthType.Neutral,
				>= '\u1F50' and <= '\u1F57' => EastAsianWidthType.Neutral,
				'\u1F59' => EastAsianWidthType.Neutral,
				'\u1F5B' => EastAsianWidthType.Neutral,
				'\u1F5D' => EastAsianWidthType.Neutral,
				>= '\u1F5F' and <= '\u1F7D' => EastAsianWidthType.Neutral,
				>= '\u1F80' and <= '\u1FB4' => EastAsianWidthType.Neutral,
				>= '\u1FB6' and <= '\u1FBC' => EastAsianWidthType.Neutral,
				'\u1FBD' => EastAsianWidthType.Neutral,
				'\u1FBE' => EastAsianWidthType.Neutral,
				>= '\u1FBF' and <= '\u1FC1' => EastAsianWidthType.Neutral,
				>= '\u1FC2' and <= '\u1FC4' => EastAsianWidthType.Neutral,
				>= '\u1FC6' and <= '\u1FCC' => EastAsianWidthType.Neutral,
				>= '\u1FCD' and <= '\u1FCF' => EastAsianWidthType.Neutral,
				>= '\u1FD0' and <= '\u1FD3' => EastAsianWidthType.Neutral,
				>= '\u1FD6' and <= '\u1FDB' => EastAsianWidthType.Neutral,
				>= '\u1FDD' and <= '\u1FDF' => EastAsianWidthType.Neutral,
				>= '\u1FE0' and <= '\u1FEC' => EastAsianWidthType.Neutral,
				>= '\u1FED' and <= '\u1FEF' => EastAsianWidthType.Neutral,
				>= '\u1FF2' and <= '\u1FF4' => EastAsianWidthType.Neutral,
				>= '\u1FF6' and <= '\u1FFC' => EastAsianWidthType.Neutral,
				>= '\u1FFD' and <= '\u1FFE' => EastAsianWidthType.Neutral,
				>= '\u2000' and <= '\u200A' => EastAsianWidthType.Neutral,
				>= '\u200B' and <= '\u200F' => EastAsianWidthType.Neutral,
				'\u2010' => EastAsianWidthType.Ambiguous,
				>= '\u2011' and <= '\u2012' => EastAsianWidthType.Neutral,
				>= '\u2013' and <= '\u2015' => EastAsianWidthType.Ambiguous,
				'\u2016' => EastAsianWidthType.Ambiguous,
				'\u2017' => EastAsianWidthType.Neutral,
				'\u2018' => EastAsianWidthType.Ambiguous,
				'\u2019' => EastAsianWidthType.Ambiguous,
				'\u201A' => EastAsianWidthType.Neutral,
				'\u201B' => EastAsianWidthType.Neutral,
				'\u201C' => EastAsianWidthType.Ambiguous,
				'\u201D' => EastAsianWidthType.Ambiguous,
				'\u201E' => EastAsianWidthType.Neutral,
				'\u201F' => EastAsianWidthType.Neutral,
				>= '\u2020' and <= '\u2022' => EastAsianWidthType.Ambiguous,
				'\u2023' => EastAsianWidthType.Neutral,
				>= '\u2024' and <= '\u2027' => EastAsianWidthType.Ambiguous,
				'\u2028' => EastAsianWidthType.Neutral,
				'\u2029' => EastAsianWidthType.Neutral,
				>= '\u202A' and <= '\u202E' => EastAsianWidthType.Neutral,
				'\u202F' => EastAsianWidthType.Neutral,
				'\u2030' => EastAsianWidthType.Ambiguous,
				'\u2031' => EastAsianWidthType.Neutral,
				>= '\u2032' and <= '\u2033' => EastAsianWidthType.Ambiguous,
				'\u2034' => EastAsianWidthType.Neutral,
				'\u2035' => EastAsianWidthType.Ambiguous,
				>= '\u2036' and <= '\u2038' => EastAsianWidthType.Neutral,
				'\u2039' => EastAsianWidthType.Neutral,
				'\u203A' => EastAsianWidthType.Neutral,
				'\u203B' => EastAsianWidthType.Ambiguous,
				>= '\u203C' and <= '\u203D' => EastAsianWidthType.Neutral,
				'\u203E' => EastAsianWidthType.Ambiguous,
				>= '\u203F' and <= '\u2040' => EastAsianWidthType.Neutral,
				>= '\u2041' and <= '\u2043' => EastAsianWidthType.Neutral,
				'\u2044' => EastAsianWidthType.Neutral,
				'\u2045' => EastAsianWidthType.Neutral,
				'\u2046' => EastAsianWidthType.Neutral,
				>= '\u2047' and <= '\u2051' => EastAsianWidthType.Neutral,
				'\u2052' => EastAsianWidthType.Neutral,
				'\u2053' => EastAsianWidthType.Neutral,
				'\u2054' => EastAsianWidthType.Neutral,
				>= '\u2055' and <= '\u205E' => EastAsianWidthType.Neutral,
				'\u205F' => EastAsianWidthType.Neutral,
				>= '\u2060' and <= '\u2064' => EastAsianWidthType.Neutral,
				>= '\u2066' and <= '\u206F' => EastAsianWidthType.Neutral,
				'\u2070' => EastAsianWidthType.Neutral,
				'\u2071' => EastAsianWidthType.Neutral,
				'\u2074' => EastAsianWidthType.Ambiguous,
				>= '\u2075' and <= '\u2079' => EastAsianWidthType.Neutral,
				>= '\u207A' and <= '\u207C' => EastAsianWidthType.Neutral,
				'\u207D' => EastAsianWidthType.Neutral,
				'\u207E' => EastAsianWidthType.Neutral,
				'\u207F' => EastAsianWidthType.Ambiguous,
				'\u2080' => EastAsianWidthType.Neutral,
				>= '\u2081' and <= '\u2084' => EastAsianWidthType.Ambiguous,
				>= '\u2085' and <= '\u2089' => EastAsianWidthType.Neutral,
				>= '\u208A' and <= '\u208C' => EastAsianWidthType.Neutral,
				'\u208D' => EastAsianWidthType.Neutral,
				'\u208E' => EastAsianWidthType.Neutral,
				>= '\u2090' and <= '\u209C' => EastAsianWidthType.Neutral,
				>= '\u20A0' and <= '\u20A8' => EastAsianWidthType.Neutral,
				'\u20A9' => EastAsianWidthType.HalfWidth,
				>= '\u20AA' and <= '\u20AB' => EastAsianWidthType.Neutral,
				'\u20AC' => EastAsianWidthType.Ambiguous,
				>= '\u20AD' and <= '\u20BF' => EastAsianWidthType.Neutral,
				>= '\u20D0' and <= '\u20DC' => EastAsianWidthType.Neutral,
				>= '\u20DD' and <= '\u20E0' => EastAsianWidthType.Neutral,
				'\u20E1' => EastAsianWidthType.Neutral,
				>= '\u20E2' and <= '\u20E4' => EastAsianWidthType.Neutral,
				>= '\u20E5' and <= '\u20F0' => EastAsianWidthType.Neutral,
				>= '\u2100' and <= '\u2101' => EastAsianWidthType.Neutral,
				'\u2102' => EastAsianWidthType.Neutral,
				'\u2103' => EastAsianWidthType.Ambiguous,
				'\u2104' => EastAsianWidthType.Neutral,
				'\u2105' => EastAsianWidthType.Ambiguous,
				'\u2106' => EastAsianWidthType.Neutral,
				'\u2107' => EastAsianWidthType.Neutral,
				'\u2108' => EastAsianWidthType.Neutral,
				'\u2109' => EastAsianWidthType.Ambiguous,
				>= '\u210A' and <= '\u2112' => EastAsianWidthType.Neutral,
				'\u2113' => EastAsianWidthType.Ambiguous,
				'\u2114' => EastAsianWidthType.Neutral,
				'\u2115' => EastAsianWidthType.Neutral,
				'\u2116' => EastAsianWidthType.Ambiguous,
				'\u2117' => EastAsianWidthType.Neutral,
				'\u2118' => EastAsianWidthType.Neutral,
				>= '\u2119' and <= '\u211D' => EastAsianWidthType.Neutral,
				>= '\u211E' and <= '\u2120' => EastAsianWidthType.Neutral,
				>= '\u2121' and <= '\u2122' => EastAsianWidthType.Ambiguous,
				'\u2123' => EastAsianWidthType.Neutral,
				'\u2124' => EastAsianWidthType.Neutral,
				'\u2125' => EastAsianWidthType.Neutral,
				'\u2126' => EastAsianWidthType.Ambiguous,
				'\u2127' => EastAsianWidthType.Neutral,
				'\u2128' => EastAsianWidthType.Neutral,
				'\u2129' => EastAsianWidthType.Neutral,
				'\u212A' => EastAsianWidthType.Neutral,
				'\u212B' => EastAsianWidthType.Ambiguous,
				>= '\u212C' and <= '\u212D' => EastAsianWidthType.Neutral,
				'\u212E' => EastAsianWidthType.Neutral,
				>= '\u212F' and <= '\u2134' => EastAsianWidthType.Neutral,
				>= '\u2135' and <= '\u2138' => EastAsianWidthType.Neutral,
				'\u2139' => EastAsianWidthType.Neutral,
				>= '\u213A' and <= '\u213B' => EastAsianWidthType.Neutral,
				>= '\u213C' and <= '\u213F' => EastAsianWidthType.Neutral,
				>= '\u2140' and <= '\u2144' => EastAsianWidthType.Neutral,
				>= '\u2145' and <= '\u2149' => EastAsianWidthType.Neutral,
				'\u214A' => EastAsianWidthType.Neutral,
				'\u214B' => EastAsianWidthType.Neutral,
				>= '\u214C' and <= '\u214D' => EastAsianWidthType.Neutral,
				'\u214E' => EastAsianWidthType.Neutral,
				'\u214F' => EastAsianWidthType.Neutral,
				>= '\u2150' and <= '\u2152' => EastAsianWidthType.Neutral,
				>= '\u2153' and <= '\u2154' => EastAsianWidthType.Ambiguous,
				>= '\u2155' and <= '\u215A' => EastAsianWidthType.Neutral,
				>= '\u215B' and <= '\u215E' => EastAsianWidthType.Ambiguous,
				'\u215F' => EastAsianWidthType.Neutral,
				>= '\u2160' and <= '\u216B' => EastAsianWidthType.Ambiguous,
				>= '\u216C' and <= '\u216F' => EastAsianWidthType.Neutral,
				>= '\u2170' and <= '\u2179' => EastAsianWidthType.Ambiguous,
				>= '\u217A' and <= '\u2182' => EastAsianWidthType.Neutral,
				>= '\u2183' and <= '\u2184' => EastAsianWidthType.Neutral,
				>= '\u2185' and <= '\u2188' => EastAsianWidthType.Neutral,
				'\u2189' => EastAsianWidthType.Ambiguous,
				>= '\u218A' and <= '\u218B' => EastAsianWidthType.Neutral,
				>= '\u2190' and <= '\u2194' => EastAsianWidthType.Ambiguous,
				>= '\u2195' and <= '\u2199' => EastAsianWidthType.Ambiguous,
				>= '\u219A' and <= '\u219B' => EastAsianWidthType.Neutral,
				>= '\u219C' and <= '\u219F' => EastAsianWidthType.Neutral,
				'\u21A0' => EastAsianWidthType.Neutral,
				>= '\u21A1' and <= '\u21A2' => EastAsianWidthType.Neutral,
				'\u21A3' => EastAsianWidthType.Neutral,
				>= '\u21A4' and <= '\u21A5' => EastAsianWidthType.Neutral,
				'\u21A6' => EastAsianWidthType.Neutral,
				>= '\u21A7' and <= '\u21AD' => EastAsianWidthType.Neutral,
				'\u21AE' => EastAsianWidthType.Neutral,
				>= '\u21AF' and <= '\u21B7' => EastAsianWidthType.Neutral,
				>= '\u21B8' and <= '\u21B9' => EastAsianWidthType.Ambiguous,
				>= '\u21BA' and <= '\u21CD' => EastAsianWidthType.Neutral,
				>= '\u21CE' and <= '\u21CF' => EastAsianWidthType.Neutral,
				>= '\u21D0' and <= '\u21D1' => EastAsianWidthType.Neutral,
				'\u21D2' => EastAsianWidthType.Ambiguous,
				'\u21D3' => EastAsianWidthType.Neutral,
				'\u21D4' => EastAsianWidthType.Ambiguous,
				>= '\u21D5' and <= '\u21E6' => EastAsianWidthType.Neutral,
				'\u21E7' => EastAsianWidthType.Ambiguous,
				>= '\u21E8' and <= '\u21F3' => EastAsianWidthType.Neutral,
				>= '\u21F4' and <= '\u21FF' => EastAsianWidthType.Neutral,
				'\u2200' => EastAsianWidthType.Ambiguous,
				'\u2201' => EastAsianWidthType.Neutral,
				>= '\u2202' and <= '\u2203' => EastAsianWidthType.Ambiguous,
				>= '\u2204' and <= '\u2206' => EastAsianWidthType.Neutral,
				>= '\u2207' and <= '\u2208' => EastAsianWidthType.Ambiguous,
				>= '\u2209' and <= '\u220A' => EastAsianWidthType.Neutral,
				'\u220B' => EastAsianWidthType.Ambiguous,
				>= '\u220C' and <= '\u220E' => EastAsianWidthType.Neutral,
				'\u220F' => EastAsianWidthType.Ambiguous,
				'\u2210' => EastAsianWidthType.Neutral,
				'\u2211' => EastAsianWidthType.Ambiguous,
				>= '\u2212' and <= '\u2214' => EastAsianWidthType.Neutral,
				'\u2215' => EastAsianWidthType.Ambiguous,
				>= '\u2216' and <= '\u2219' => EastAsianWidthType.Neutral,
				'\u221A' => EastAsianWidthType.Ambiguous,
				>= '\u221B' and <= '\u221C' => EastAsianWidthType.Neutral,
				>= '\u221D' and <= '\u2220' => EastAsianWidthType.Ambiguous,
				>= '\u2221' and <= '\u2222' => EastAsianWidthType.Neutral,
				'\u2223' => EastAsianWidthType.Ambiguous,
				'\u2224' => EastAsianWidthType.Neutral,
				'\u2225' => EastAsianWidthType.Ambiguous,
				'\u2226' => EastAsianWidthType.Neutral,
				>= '\u2227' and <= '\u222C' => EastAsianWidthType.Ambiguous,
				'\u222D' => EastAsianWidthType.Neutral,
				'\u222E' => EastAsianWidthType.Ambiguous,
				>= '\u222F' and <= '\u2233' => EastAsianWidthType.Neutral,
				>= '\u2234' and <= '\u2237' => EastAsianWidthType.Ambiguous,
				>= '\u2238' and <= '\u223B' => EastAsianWidthType.Neutral,
				>= '\u223C' and <= '\u223D' => EastAsianWidthType.Ambiguous,
				>= '\u223E' and <= '\u2247' => EastAsianWidthType.Neutral,
				'\u2248' => EastAsianWidthType.Ambiguous,
				>= '\u2249' and <= '\u224B' => EastAsianWidthType.Neutral,
				'\u224C' => EastAsianWidthType.Ambiguous,
				>= '\u224D' and <= '\u2251' => EastAsianWidthType.Neutral,
				'\u2252' => EastAsianWidthType.Ambiguous,
				>= '\u2253' and <= '\u225F' => EastAsianWidthType.Neutral,
				>= '\u2260' and <= '\u2261' => EastAsianWidthType.Ambiguous,
				>= '\u2262' and <= '\u2263' => EastAsianWidthType.Neutral,
				>= '\u2264' and <= '\u2267' => EastAsianWidthType.Ambiguous,
				>= '\u2268' and <= '\u2269' => EastAsianWidthType.Neutral,
				>= '\u226A' and <= '\u226B' => EastAsianWidthType.Ambiguous,
				>= '\u226C' and <= '\u226D' => EastAsianWidthType.Neutral,
				>= '\u226E' and <= '\u226F' => EastAsianWidthType.Ambiguous,
				>= '\u2270' and <= '\u2281' => EastAsianWidthType.Neutral,
				>= '\u2282' and <= '\u2283' => EastAsianWidthType.Ambiguous,
				>= '\u2284' and <= '\u2285' => EastAsianWidthType.Neutral,
				>= '\u2286' and <= '\u2287' => EastAsianWidthType.Ambiguous,
				>= '\u2288' and <= '\u2294' => EastAsianWidthType.Neutral,
				'\u2295' => EastAsianWidthType.Ambiguous,
				>= '\u2296' and <= '\u2298' => EastAsianWidthType.Neutral,
				'\u2299' => EastAsianWidthType.Ambiguous,
				>= '\u229A' and <= '\u22A4' => EastAsianWidthType.Neutral,
				'\u22A5' => EastAsianWidthType.Ambiguous,
				>= '\u22A6' and <= '\u22BE' => EastAsianWidthType.Neutral,
				'\u22BF' => EastAsianWidthType.Ambiguous,
				>= '\u22C0' and <= '\u22FF' => EastAsianWidthType.Neutral,
				>= '\u2300' and <= '\u2307' => EastAsianWidthType.Neutral,
				'\u2308' => EastAsianWidthType.Neutral,
				'\u2309' => EastAsianWidthType.Neutral,
				'\u230A' => EastAsianWidthType.Neutral,
				'\u230B' => EastAsianWidthType.Neutral,
				>= '\u230C' and <= '\u2311' => EastAsianWidthType.Neutral,
				'\u2312' => EastAsianWidthType.Ambiguous,
				>= '\u2313' and <= '\u2319' => EastAsianWidthType.Neutral,
				>= '\u231A' and <= '\u231B' => EastAsianWidthType.Wide,
				>= '\u231C' and <= '\u231F' => EastAsianWidthType.Neutral,
				>= '\u2320' and <= '\u2321' => EastAsianWidthType.Neutral,
				>= '\u2322' and <= '\u2328' => EastAsianWidthType.Neutral,
				'\u2329' => EastAsianWidthType.Wide,
				'\u232A' => EastAsianWidthType.Wide,
				>= '\u232B' and <= '\u237B' => EastAsianWidthType.Neutral,
				'\u237C' => EastAsianWidthType.Neutral,
				>= '\u237D' and <= '\u239A' => EastAsianWidthType.Neutral,
				>= '\u239B' and <= '\u23B3' => EastAsianWidthType.Neutral,
				>= '\u23B4' and <= '\u23DB' => EastAsianWidthType.Neutral,
				>= '\u23DC' and <= '\u23E1' => EastAsianWidthType.Neutral,
				>= '\u23E2' and <= '\u23E8' => EastAsianWidthType.Neutral,
				>= '\u23E9' and <= '\u23EC' => EastAsianWidthType.Wide,
				>= '\u23ED' and <= '\u23EF' => EastAsianWidthType.Neutral,
				'\u23F0' => EastAsianWidthType.Wide,
				>= '\u23F1' and <= '\u23F2' => EastAsianWidthType.Neutral,
				'\u23F3' => EastAsianWidthType.Wide,
				>= '\u23F4' and <= '\u23FF' => EastAsianWidthType.Neutral,
				>= '\u2400' and <= '\u2426' => EastAsianWidthType.Neutral,
				>= '\u2440' and <= '\u244A' => EastAsianWidthType.Neutral,
				>= '\u2460' and <= '\u249B' => EastAsianWidthType.Ambiguous,
				>= '\u249C' and <= '\u24E9' => EastAsianWidthType.Ambiguous,
				'\u24EA' => EastAsianWidthType.Neutral,
				>= '\u24EB' and <= '\u24FF' => EastAsianWidthType.Ambiguous,
				>= '\u2500' and <= '\u254B' => EastAsianWidthType.Ambiguous,
				>= '\u254C' and <= '\u254F' => EastAsianWidthType.Neutral,
				>= '\u2550' and <= '\u2573' => EastAsianWidthType.Ambiguous,
				>= '\u2574' and <= '\u257F' => EastAsianWidthType.Neutral,
				>= '\u2580' and <= '\u258F' => EastAsianWidthType.Ambiguous,
				>= '\u2590' and <= '\u2591' => EastAsianWidthType.Neutral,
				>= '\u2592' and <= '\u2595' => EastAsianWidthType.Ambiguous,
				>= '\u2596' and <= '\u259F' => EastAsianWidthType.Neutral,
				>= '\u25A0' and <= '\u25A1' => EastAsianWidthType.Ambiguous,
				'\u25A2' => EastAsianWidthType.Neutral,
				>= '\u25A3' and <= '\u25A9' => EastAsianWidthType.Ambiguous,
				>= '\u25AA' and <= '\u25B1' => EastAsianWidthType.Neutral,
				>= '\u25B2' and <= '\u25B3' => EastAsianWidthType.Ambiguous,
				>= '\u25B4' and <= '\u25B5' => EastAsianWidthType.Neutral,
				'\u25B6' => EastAsianWidthType.Ambiguous,
				'\u25B7' => EastAsianWidthType.Ambiguous,
				>= '\u25B8' and <= '\u25BB' => EastAsianWidthType.Neutral,
				>= '\u25BC' and <= '\u25BD' => EastAsianWidthType.Ambiguous,
				>= '\u25BE' and <= '\u25BF' => EastAsianWidthType.Neutral,
				'\u25C0' => EastAsianWidthType.Ambiguous,
				'\u25C1' => EastAsianWidthType.Ambiguous,
				>= '\u25C2' and <= '\u25C5' => EastAsianWidthType.Neutral,
				>= '\u25C6' and <= '\u25C8' => EastAsianWidthType.Ambiguous,
				>= '\u25C9' and <= '\u25CA' => EastAsianWidthType.Neutral,
				'\u25CB' => EastAsianWidthType.Ambiguous,
				>= '\u25CC' and <= '\u25CD' => EastAsianWidthType.Neutral,
				>= '\u25CE' and <= '\u25D1' => EastAsianWidthType.Ambiguous,
				>= '\u25D2' and <= '\u25E1' => EastAsianWidthType.Neutral,
				>= '\u25E2' and <= '\u25E5' => EastAsianWidthType.Ambiguous,
				>= '\u25E6' and <= '\u25EE' => EastAsianWidthType.Neutral,
				'\u25EF' => EastAsianWidthType.Ambiguous,
				>= '\u25F0' and <= '\u25F7' => EastAsianWidthType.Neutral,
				>= '\u25F8' and <= '\u25FC' => EastAsianWidthType.Neutral,
				>= '\u25FD' and <= '\u25FE' => EastAsianWidthType.Wide,
				'\u25FF' => EastAsianWidthType.Neutral,
				>= '\u2600' and <= '\u2604' => EastAsianWidthType.Neutral,
				>= '\u2605' and <= '\u2606' => EastAsianWidthType.Ambiguous,
				>= '\u2607' and <= '\u2608' => EastAsianWidthType.Neutral,
				'\u2609' => EastAsianWidthType.Ambiguous,
				>= '\u260A' and <= '\u260D' => EastAsianWidthType.Neutral,
				>= '\u260E' and <= '\u260F' => EastAsianWidthType.Ambiguous,
				>= '\u2610' and <= '\u2613' => EastAsianWidthType.Neutral,
				>= '\u2614' and <= '\u2615' => EastAsianWidthType.Wide,
				>= '\u2616' and <= '\u261B' => EastAsianWidthType.Neutral,
				'\u261C' => EastAsianWidthType.Ambiguous,
				'\u261D' => EastAsianWidthType.Neutral,
				'\u261E' => EastAsianWidthType.Ambiguous,
				>= '\u261F' and <= '\u263F' => EastAsianWidthType.Neutral,
				'\u2640' => EastAsianWidthType.Ambiguous,
				'\u2641' => EastAsianWidthType.Neutral,
				'\u2642' => EastAsianWidthType.Ambiguous,
				>= '\u2643' and <= '\u2647' => EastAsianWidthType.Neutral,
				>= '\u2648' and <= '\u2653' => EastAsianWidthType.Wide,
				>= '\u2654' and <= '\u265F' => EastAsianWidthType.Neutral,
				>= '\u2660' and <= '\u2661' => EastAsianWidthType.Ambiguous,
				'\u2662' => EastAsianWidthType.Neutral,
				>= '\u2663' and <= '\u2665' => EastAsianWidthType.Ambiguous,
				'\u2666' => EastAsianWidthType.Neutral,
				>= '\u2667' and <= '\u266A' => EastAsianWidthType.Ambiguous,
				'\u266B' => EastAsianWidthType.Neutral,
				>= '\u266C' and <= '\u266D' => EastAsianWidthType.Ambiguous,
				'\u266E' => EastAsianWidthType.Neutral,
				'\u266F' => EastAsianWidthType.Ambiguous,
				>= '\u2670' and <= '\u267E' => EastAsianWidthType.Neutral,
				'\u267F' => EastAsianWidthType.Wide,
				>= '\u2680' and <= '\u2692' => EastAsianWidthType.Neutral,
				'\u2693' => EastAsianWidthType.Wide,
				>= '\u2694' and <= '\u269D' => EastAsianWidthType.Neutral,
				>= '\u269E' and <= '\u269F' => EastAsianWidthType.Ambiguous,
				'\u26A0' => EastAsianWidthType.Neutral,
				'\u26A1' => EastAsianWidthType.Wide,
				>= '\u26A2' and <= '\u26A9' => EastAsianWidthType.Neutral,
				>= '\u26AA' and <= '\u26AB' => EastAsianWidthType.Wide,
				>= '\u26AC' and <= '\u26BC' => EastAsianWidthType.Neutral,
				>= '\u26BD' and <= '\u26BE' => EastAsianWidthType.Wide,
				'\u26BF' => EastAsianWidthType.Ambiguous,
				>= '\u26C0' and <= '\u26C3' => EastAsianWidthType.Neutral,
				>= '\u26C4' and <= '\u26C5' => EastAsianWidthType.Wide,
				>= '\u26C6' and <= '\u26CD' => EastAsianWidthType.Ambiguous,
				'\u26CE' => EastAsianWidthType.Wide,
				>= '\u26CF' and <= '\u26D3' => EastAsianWidthType.Ambiguous,
				'\u26D4' => EastAsianWidthType.Wide,
				>= '\u26D5' and <= '\u26E1' => EastAsianWidthType.Ambiguous,
				'\u26E2' => EastAsianWidthType.Neutral,
				'\u26E3' => EastAsianWidthType.Ambiguous,
				>= '\u26E4' and <= '\u26E7' => EastAsianWidthType.Neutral,
				>= '\u26E8' and <= '\u26E9' => EastAsianWidthType.Ambiguous,
				'\u26EA' => EastAsianWidthType.Wide,
				>= '\u26EB' and <= '\u26F1' => EastAsianWidthType.Ambiguous,
				>= '\u26F2' and <= '\u26F3' => EastAsianWidthType.Wide,
				'\u26F4' => EastAsianWidthType.Ambiguous,
				'\u26F5' => EastAsianWidthType.Wide,
				>= '\u26F6' and <= '\u26F9' => EastAsianWidthType.Ambiguous,
				'\u26FA' => EastAsianWidthType.Wide,
				>= '\u26FB' and <= '\u26FC' => EastAsianWidthType.Ambiguous,
				'\u26FD' => EastAsianWidthType.Wide,
				>= '\u26FE' and <= '\u26FF' => EastAsianWidthType.Ambiguous,
				>= '\u2700' and <= '\u2704' => EastAsianWidthType.Neutral,
				'\u2705' => EastAsianWidthType.Wide,
				>= '\u2706' and <= '\u2709' => EastAsianWidthType.Neutral,
				>= '\u270A' and <= '\u270B' => EastAsianWidthType.Wide,
				>= '\u270C' and <= '\u2727' => EastAsianWidthType.Neutral,
				'\u2728' => EastAsianWidthType.Wide,
				>= '\u2729' and <= '\u273C' => EastAsianWidthType.Neutral,
				'\u273D' => EastAsianWidthType.Ambiguous,
				>= '\u273E' and <= '\u274B' => EastAsianWidthType.Neutral,
				'\u274C' => EastAsianWidthType.Wide,
				'\u274D' => EastAsianWidthType.Neutral,
				'\u274E' => EastAsianWidthType.Wide,
				>= '\u274F' and <= '\u2752' => EastAsianWidthType.Neutral,
				>= '\u2753' and <= '\u2755' => EastAsianWidthType.Wide,
				'\u2756' => EastAsianWidthType.Neutral,
				'\u2757' => EastAsianWidthType.Wide,
				>= '\u2758' and <= '\u2767' => EastAsianWidthType.Neutral,
				'\u2768' => EastAsianWidthType.Neutral,
				'\u2769' => EastAsianWidthType.Neutral,
				'\u276A' => EastAsianWidthType.Neutral,
				'\u276B' => EastAsianWidthType.Neutral,
				'\u276C' => EastAsianWidthType.Neutral,
				'\u276D' => EastAsianWidthType.Neutral,
				'\u276E' => EastAsianWidthType.Neutral,
				'\u276F' => EastAsianWidthType.Neutral,
				'\u2770' => EastAsianWidthType.Neutral,
				'\u2771' => EastAsianWidthType.Neutral,
				'\u2772' => EastAsianWidthType.Neutral,
				'\u2773' => EastAsianWidthType.Neutral,
				'\u2774' => EastAsianWidthType.Neutral,
				'\u2775' => EastAsianWidthType.Neutral,
				>= '\u2776' and <= '\u277F' => EastAsianWidthType.Ambiguous,
				>= '\u2780' and <= '\u2793' => EastAsianWidthType.Neutral,
				'\u2794' => EastAsianWidthType.Neutral,
				>= '\u2795' and <= '\u2797' => EastAsianWidthType.Wide,
				>= '\u2798' and <= '\u27AF' => EastAsianWidthType.Neutral,
				'\u27B0' => EastAsianWidthType.Wide,
				>= '\u27B1' and <= '\u27BE' => EastAsianWidthType.Neutral,
				'\u27BF' => EastAsianWidthType.Wide,
				>= '\u27C0' and <= '\u27C4' => EastAsianWidthType.Neutral,
				'\u27C5' => EastAsianWidthType.Neutral,
				'\u27C6' => EastAsianWidthType.Neutral,
				>= '\u27C7' and <= '\u27E5' => EastAsianWidthType.Neutral,
				'\u27E6' => EastAsianWidthType.Narrow,
				'\u27E7' => EastAsianWidthType.Narrow,
				'\u27E8' => EastAsianWidthType.Narrow,
				'\u27E9' => EastAsianWidthType.Narrow,
				'\u27EA' => EastAsianWidthType.Narrow,
				'\u27EB' => EastAsianWidthType.Narrow,
				'\u27EC' => EastAsianWidthType.Narrow,
				'\u27ED' => EastAsianWidthType.Narrow,
				'\u27EE' => EastAsianWidthType.Neutral,
				'\u27EF' => EastAsianWidthType.Neutral,
				>= '\u27F0' and <= '\u27FF' => EastAsianWidthType.Neutral,
				>= '\u2800' and <= '\u28FF' => EastAsianWidthType.Neutral,
				>= '\u2900' and <= '\u297F' => EastAsianWidthType.Neutral,
				>= '\u2980' and <= '\u2982' => EastAsianWidthType.Neutral,
				'\u2983' => EastAsianWidthType.Neutral,
				'\u2984' => EastAsianWidthType.Neutral,
				'\u2985' => EastAsianWidthType.Narrow,
				'\u2986' => EastAsianWidthType.Narrow,
				'\u2987' => EastAsianWidthType.Neutral,
				'\u2988' => EastAsianWidthType.Neutral,
				'\u2989' => EastAsianWidthType.Neutral,
				'\u298A' => EastAsianWidthType.Neutral,
				'\u298B' => EastAsianWidthType.Neutral,
				'\u298C' => EastAsianWidthType.Neutral,
				'\u298D' => EastAsianWidthType.Neutral,
				'\u298E' => EastAsianWidthType.Neutral,
				'\u298F' => EastAsianWidthType.Neutral,
				'\u2990' => EastAsianWidthType.Neutral,
				'\u2991' => EastAsianWidthType.Neutral,
				'\u2992' => EastAsianWidthType.Neutral,
				'\u2993' => EastAsianWidthType.Neutral,
				'\u2994' => EastAsianWidthType.Neutral,
				'\u2995' => EastAsianWidthType.Neutral,
				'\u2996' => EastAsianWidthType.Neutral,
				'\u2997' => EastAsianWidthType.Neutral,
				'\u2998' => EastAsianWidthType.Neutral,
				>= '\u2999' and <= '\u29D7' => EastAsianWidthType.Neutral,
				'\u29D8' => EastAsianWidthType.Neutral,
				'\u29D9' => EastAsianWidthType.Neutral,
				'\u29DA' => EastAsianWidthType.Neutral,
				'\u29DB' => EastAsianWidthType.Neutral,
				>= '\u29DC' and <= '\u29FB' => EastAsianWidthType.Neutral,
				'\u29FC' => EastAsianWidthType.Neutral,
				'\u29FD' => EastAsianWidthType.Neutral,
				>= '\u29FE' and <= '\u29FF' => EastAsianWidthType.Neutral,
				>= '\u2A00' and <= '\u2AFF' => EastAsianWidthType.Neutral,
				>= '\u2B00' and <= '\u2B1A' => EastAsianWidthType.Neutral,
				>= '\u2B1B' and <= '\u2B1C' => EastAsianWidthType.Wide,
				>= '\u2B1D' and <= '\u2B2F' => EastAsianWidthType.Neutral,
				>= '\u2B30' and <= '\u2B44' => EastAsianWidthType.Neutral,
				>= '\u2B45' and <= '\u2B46' => EastAsianWidthType.Neutral,
				>= '\u2B47' and <= '\u2B4C' => EastAsianWidthType.Neutral,
				>= '\u2B4D' and <= '\u2B4F' => EastAsianWidthType.Neutral,
				'\u2B50' => EastAsianWidthType.Wide,
				>= '\u2B51' and <= '\u2B54' => EastAsianWidthType.Neutral,
				'\u2B55' => EastAsianWidthType.Wide,
				>= '\u2B56' and <= '\u2B59' => EastAsianWidthType.Ambiguous,
				>= '\u2B5A' and <= '\u2B73' => EastAsianWidthType.Neutral,
				>= '\u2B76' and <= '\u2B95' => EastAsianWidthType.Neutral,
				>= '\u2B98' and <= '\u2BFF' => EastAsianWidthType.Neutral,
				>= '\u2C00' and <= '\u2C2E' => EastAsianWidthType.Neutral,
				>= '\u2C30' and <= '\u2C5E' => EastAsianWidthType.Neutral,
				>= '\u2C60' and <= '\u2C7B' => EastAsianWidthType.Neutral,
				>= '\u2C7C' and <= '\u2C7D' => EastAsianWidthType.Neutral,
				>= '\u2C7E' and <= '\u2C7F' => EastAsianWidthType.Neutral,
				>= '\u2C80' and <= '\u2CE4' => EastAsianWidthType.Neutral,
				>= '\u2CE5' and <= '\u2CEA' => EastAsianWidthType.Neutral,
				>= '\u2CEB' and <= '\u2CEE' => EastAsianWidthType.Neutral,
				>= '\u2CEF' and <= '\u2CF1' => EastAsianWidthType.Neutral,
				>= '\u2CF2' and <= '\u2CF3' => EastAsianWidthType.Neutral,
				>= '\u2CF9' and <= '\u2CFC' => EastAsianWidthType.Neutral,
				'\u2CFD' => EastAsianWidthType.Neutral,
				>= '\u2CFE' and <= '\u2CFF' => EastAsianWidthType.Neutral,
				>= '\u2D00' and <= '\u2D25' => EastAsianWidthType.Neutral,
				'\u2D27' => EastAsianWidthType.Neutral,
				'\u2D2D' => EastAsianWidthType.Neutral,
				>= '\u2D30' and <= '\u2D67' => EastAsianWidthType.Neutral,
				'\u2D6F' => EastAsianWidthType.Neutral,
				'\u2D70' => EastAsianWidthType.Neutral,
				'\u2D7F' => EastAsianWidthType.Neutral,
				>= '\u2D80' and <= '\u2D96' => EastAsianWidthType.Neutral,
				>= '\u2DA0' and <= '\u2DA6' => EastAsianWidthType.Neutral,
				>= '\u2DA8' and <= '\u2DAE' => EastAsianWidthType.Neutral,
				>= '\u2DB0' and <= '\u2DB6' => EastAsianWidthType.Neutral,
				>= '\u2DB8' and <= '\u2DBE' => EastAsianWidthType.Neutral,
				>= '\u2DC0' and <= '\u2DC6' => EastAsianWidthType.Neutral,
				>= '\u2DC8' and <= '\u2DCE' => EastAsianWidthType.Neutral,
				>= '\u2DD0' and <= '\u2DD6' => EastAsianWidthType.Neutral,
				>= '\u2DD8' and <= '\u2DDE' => EastAsianWidthType.Neutral,
				>= '\u2DE0' and <= '\u2DFF' => EastAsianWidthType.Neutral,
				>= '\u2E00' and <= '\u2E01' => EastAsianWidthType.Neutral,
				'\u2E02' => EastAsianWidthType.Neutral,
				'\u2E03' => EastAsianWidthType.Neutral,
				'\u2E04' => EastAsianWidthType.Neutral,
				'\u2E05' => EastAsianWidthType.Neutral,
				>= '\u2E06' and <= '\u2E08' => EastAsianWidthType.Neutral,
				'\u2E09' => EastAsianWidthType.Neutral,
				'\u2E0A' => EastAsianWidthType.Neutral,
				'\u2E0B' => EastAsianWidthType.Neutral,
				'\u2E0C' => EastAsianWidthType.Neutral,
				'\u2E0D' => EastAsianWidthType.Neutral,
				>= '\u2E0E' and <= '\u2E16' => EastAsianWidthType.Neutral,
				'\u2E17' => EastAsianWidthType.Neutral,
				>= '\u2E18' and <= '\u2E19' => EastAsianWidthType.Neutral,
				'\u2E1A' => EastAsianWidthType.Neutral,
				'\u2E1B' => EastAsianWidthType.Neutral,
				'\u2E1C' => EastAsianWidthType.Neutral,
				'\u2E1D' => EastAsianWidthType.Neutral,
				>= '\u2E1E' and <= '\u2E1F' => EastAsianWidthType.Neutral,
				'\u2E20' => EastAsianWidthType.Neutral,
				'\u2E21' => EastAsianWidthType.Neutral,
				'\u2E22' => EastAsianWidthType.Neutral,
				'\u2E23' => EastAsianWidthType.Neutral,
				'\u2E24' => EastAsianWidthType.Neutral,
				'\u2E25' => EastAsianWidthType.Neutral,
				'\u2E26' => EastAsianWidthType.Neutral,
				'\u2E27' => EastAsianWidthType.Neutral,
				'\u2E28' => EastAsianWidthType.Neutral,
				'\u2E29' => EastAsianWidthType.Neutral,
				>= '\u2E2A' and <= '\u2E2E' => EastAsianWidthType.Neutral,
				'\u2E2F' => EastAsianWidthType.Neutral,
				>= '\u2E30' and <= '\u2E39' => EastAsianWidthType.Neutral,
				>= '\u2E3A' and <= '\u2E3B' => EastAsianWidthType.Neutral,
				>= '\u2E3C' and <= '\u2E3F' => EastAsianWidthType.Neutral,
				'\u2E40' => EastAsianWidthType.Neutral,
				'\u2E41' => EastAsianWidthType.Neutral,
				'\u2E42' => EastAsianWidthType.Neutral,
				>= '\u2E43' and <= '\u2E4F' => EastAsianWidthType.Neutral,
				>= '\u2E80' and <= '\u2E99' => EastAsianWidthType.Wide,
				>= '\u2E9B' and <= '\u2EF3' => EastAsianWidthType.Wide,
				>= '\u2F00' and <= '\u2FD5' => EastAsianWidthType.Wide,
				>= '\u2FF0' and <= '\u2FFB' => EastAsianWidthType.Wide,
				'\u3000' => EastAsianWidthType.FullWidth,
				>= '\u3001' and <= '\u3003' => EastAsianWidthType.Wide,
				'\u3004' => EastAsianWidthType.Wide,
				'\u3005' => EastAsianWidthType.Wide,
				'\u3006' => EastAsianWidthType.Wide,
				'\u3007' => EastAsianWidthType.Wide,
				'\u3008' => EastAsianWidthType.Wide,
				'\u3009' => EastAsianWidthType.Wide,
				'\u300A' => EastAsianWidthType.Wide,
				'\u300B' => EastAsianWidthType.Wide,
				'\u300C' => EastAsianWidthType.Wide,
				'\u300D' => EastAsianWidthType.Wide,
				'\u300E' => EastAsianWidthType.Wide,
				'\u300F' => EastAsianWidthType.Wide,
				'\u3010' => EastAsianWidthType.Wide,
				'\u3011' => EastAsianWidthType.Wide,
				>= '\u3012' and <= '\u3013' => EastAsianWidthType.Wide,
				'\u3014' => EastAsianWidthType.Wide,
				'\u3015' => EastAsianWidthType.Wide,
				'\u3016' => EastAsianWidthType.Wide,
				'\u3017' => EastAsianWidthType.Wide,
				'\u3018' => EastAsianWidthType.Wide,
				'\u3019' => EastAsianWidthType.Wide,
				'\u301A' => EastAsianWidthType.Wide,
				'\u301B' => EastAsianWidthType.Wide,
				'\u301C' => EastAsianWidthType.Wide,
				'\u301D' => EastAsianWidthType.Wide,
				>= '\u301E' and <= '\u301F' => EastAsianWidthType.Wide,
				'\u3020' => EastAsianWidthType.Wide,
				>= '\u3021' and <= '\u3029' => EastAsianWidthType.Wide,
				>= '\u302A' and <= '\u302D' => EastAsianWidthType.Wide,
				>= '\u302E' and <= '\u302F' => EastAsianWidthType.Wide,
				'\u3030' => EastAsianWidthType.Wide,
				>= '\u3031' and <= '\u3035' => EastAsianWidthType.Wide,
				>= '\u3036' and <= '\u3037' => EastAsianWidthType.Wide,
				>= '\u3038' and <= '\u303A' => EastAsianWidthType.Wide,
				'\u303B' => EastAsianWidthType.Wide,
				'\u303C' => EastAsianWidthType.Wide,
				'\u303D' => EastAsianWidthType.Wide,
				'\u303E' => EastAsianWidthType.Wide,
				'\u303F' => EastAsianWidthType.Neutral,
				>= '\u3041' and <= '\u3096' => EastAsianWidthType.Wide,
				>= '\u3099' and <= '\u309A' => EastAsianWidthType.Wide,
				>= '\u309B' and <= '\u309C' => EastAsianWidthType.Wide,
				>= '\u309D' and <= '\u309E' => EastAsianWidthType.Wide,
				'\u309F' => EastAsianWidthType.Wide,
				'\u30A0' => EastAsianWidthType.Wide,
				>= '\u30A1' and <= '\u30FA' => EastAsianWidthType.Wide,
				'\u30FB' => EastAsianWidthType.Wide,
				>= '\u30FC' and <= '\u30FE' => EastAsianWidthType.Wide,
				'\u30FF' => EastAsianWidthType.Wide,
				>= '\u3105' and <= '\u312F' => EastAsianWidthType.Wide,
				>= '\u3131' and <= '\u318E' => EastAsianWidthType.Wide,
				>= '\u3190' and <= '\u3191' => EastAsianWidthType.Wide,
				>= '\u3192' and <= '\u3195' => EastAsianWidthType.Wide,
				>= '\u3196' and <= '\u319F' => EastAsianWidthType.Wide,
				>= '\u31A0' and <= '\u31BA' => EastAsianWidthType.Wide,
				>= '\u31C0' and <= '\u31E3' => EastAsianWidthType.Wide,
				>= '\u31F0' and <= '\u31FF' => EastAsianWidthType.Wide,
				>= '\u3200' and <= '\u321E' => EastAsianWidthType.Wide,
				>= '\u3220' and <= '\u3229' => EastAsianWidthType.Wide,
				>= '\u322A' and <= '\u3247' => EastAsianWidthType.Wide,
				>= '\u3248' and <= '\u324F' => EastAsianWidthType.Ambiguous,
				'\u3250' => EastAsianWidthType.Wide,
				>= '\u3251' and <= '\u325F' => EastAsianWidthType.Wide,
				>= '\u3260' and <= '\u327F' => EastAsianWidthType.Wide,
				>= '\u3280' and <= '\u3289' => EastAsianWidthType.Wide,
				>= '\u328A' and <= '\u32B0' => EastAsianWidthType.Wide,
				>= '\u32B1' and <= '\u32BF' => EastAsianWidthType.Wide,
				>= '\u32C0' and <= '\u32FF' => EastAsianWidthType.Wide,
				>= '\u3300' and <= '\u33FF' => EastAsianWidthType.Wide,
				>= '\u3400' and <= '\u4DB5' => EastAsianWidthType.Wide,
				>= '\u4DB6' and <= '\u4DBF' => EastAsianWidthType.Wide,
				>= '\u4DC0' and <= '\u4DFF' => EastAsianWidthType.Neutral,
				>= '\u4E00' and <= '\u9FEF' => EastAsianWidthType.Wide,
				>= '\u9FF0' and <= '\u9FFF' => EastAsianWidthType.Wide,
				>= '\uA000' and <= '\uA014' => EastAsianWidthType.Wide,
				'\uA015' => EastAsianWidthType.Wide,
				>= '\uA016' and <= '\uA48C' => EastAsianWidthType.Wide,
				>= '\uA490' and <= '\uA4C6' => EastAsianWidthType.Wide,
				>= '\uA4D0' and <= '\uA4F7' => EastAsianWidthType.Neutral,
				>= '\uA4F8' and <= '\uA4FD' => EastAsianWidthType.Neutral,
				>= '\uA4FE' and <= '\uA4FF' => EastAsianWidthType.Neutral,
				>= '\uA500' and <= '\uA60B' => EastAsianWidthType.Neutral,
				'\uA60C' => EastAsianWidthType.Neutral,
				>= '\uA60D' and <= '\uA60F' => EastAsianWidthType.Neutral,
				>= '\uA610' and <= '\uA61F' => EastAsianWidthType.Neutral,
				>= '\uA620' and <= '\uA629' => EastAsianWidthType.Neutral,
				>= '\uA62A' and <= '\uA62B' => EastAsianWidthType.Neutral,
				>= '\uA640' and <= '\uA66D' => EastAsianWidthType.Neutral,
				'\uA66E' => EastAsianWidthType.Neutral,
				'\uA66F' => EastAsianWidthType.Neutral,
				>= '\uA670' and <= '\uA672' => EastAsianWidthType.Neutral,
				'\uA673' => EastAsianWidthType.Neutral,
				>= '\uA674' and <= '\uA67D' => EastAsianWidthType.Neutral,
				'\uA67E' => EastAsianWidthType.Neutral,
				'\uA67F' => EastAsianWidthType.Neutral,
				>= '\uA680' and <= '\uA69B' => EastAsianWidthType.Neutral,
				>= '\uA69C' and <= '\uA69D' => EastAsianWidthType.Neutral,
				>= '\uA69E' and <= '\uA69F' => EastAsianWidthType.Neutral,
				>= '\uA6A0' and <= '\uA6E5' => EastAsianWidthType.Neutral,
				>= '\uA6E6' and <= '\uA6EF' => EastAsianWidthType.Neutral,
				>= '\uA6F0' and <= '\uA6F1' => EastAsianWidthType.Neutral,
				>= '\uA6F2' and <= '\uA6F7' => EastAsianWidthType.Neutral,
				>= '\uA700' and <= '\uA716' => EastAsianWidthType.Neutral,
				>= '\uA717' and <= '\uA71F' => EastAsianWidthType.Neutral,
				>= '\uA720' and <= '\uA721' => EastAsianWidthType.Neutral,
				>= '\uA722' and <= '\uA76F' => EastAsianWidthType.Neutral,
				'\uA770' => EastAsianWidthType.Neutral,
				>= '\uA771' and <= '\uA787' => EastAsianWidthType.Neutral,
				'\uA788' => EastAsianWidthType.Neutral,
				>= '\uA789' and <= '\uA78A' => EastAsianWidthType.Neutral,
				>= '\uA78B' and <= '\uA78E' => EastAsianWidthType.Neutral,
				'\uA78F' => EastAsianWidthType.Neutral,
				>= '\uA790' and <= '\uA7BF' => EastAsianWidthType.Neutral,
				>= '\uA7C2' and <= '\uA7C6' => EastAsianWidthType.Neutral,
				'\uA7F7' => EastAsianWidthType.Neutral,
				>= '\uA7F8' and <= '\uA7F9' => EastAsianWidthType.Neutral,
				'\uA7FA' => EastAsianWidthType.Neutral,
				>= '\uA7FB' and <= '\uA7FF' => EastAsianWidthType.Neutral,
				>= '\uA800' and <= '\uA801' => EastAsianWidthType.Neutral,
				'\uA802' => EastAsianWidthType.Neutral,
				>= '\uA803' and <= '\uA805' => EastAsianWidthType.Neutral,
				'\uA806' => EastAsianWidthType.Neutral,
				>= '\uA807' and <= '\uA80A' => EastAsianWidthType.Neutral,
				'\uA80B' => EastAsianWidthType.Neutral,
				>= '\uA80C' and <= '\uA822' => EastAsianWidthType.Neutral,
				>= '\uA823' and <= '\uA824' => EastAsianWidthType.Neutral,
				>= '\uA825' and <= '\uA826' => EastAsianWidthType.Neutral,
				'\uA827' => EastAsianWidthType.Neutral,
				>= '\uA828' and <= '\uA82B' => EastAsianWidthType.Neutral,
				>= '\uA830' and <= '\uA835' => EastAsianWidthType.Neutral,
				>= '\uA836' and <= '\uA837' => EastAsianWidthType.Neutral,
				'\uA838' => EastAsianWidthType.Neutral,
				'\uA839' => EastAsianWidthType.Neutral,
				>= '\uA840' and <= '\uA873' => EastAsianWidthType.Neutral,
				>= '\uA874' and <= '\uA877' => EastAsianWidthType.Neutral,
				>= '\uA880' and <= '\uA881' => EastAsianWidthType.Neutral,
				>= '\uA882' and <= '\uA8B3' => EastAsianWidthType.Neutral,
				>= '\uA8B4' and <= '\uA8C3' => EastAsianWidthType.Neutral,
				>= '\uA8C4' and <= '\uA8C5' => EastAsianWidthType.Neutral,
				>= '\uA8CE' and <= '\uA8CF' => EastAsianWidthType.Neutral,
				>= '\uA8D0' and <= '\uA8D9' => EastAsianWidthType.Neutral,
				>= '\uA8E0' and <= '\uA8F1' => EastAsianWidthType.Neutral,
				>= '\uA8F2' and <= '\uA8F7' => EastAsianWidthType.Neutral,
				>= '\uA8F8' and <= '\uA8FA' => EastAsianWidthType.Neutral,
				'\uA8FB' => EastAsianWidthType.Neutral,
				'\uA8FC' => EastAsianWidthType.Neutral,
				>= '\uA8FD' and <= '\uA8FE' => EastAsianWidthType.Neutral,
				'\uA8FF' => EastAsianWidthType.Neutral,
				>= '\uA900' and <= '\uA909' => EastAsianWidthType.Neutral,
				>= '\uA90A' and <= '\uA925' => EastAsianWidthType.Neutral,
				>= '\uA926' and <= '\uA92D' => EastAsianWidthType.Neutral,
				>= '\uA92E' and <= '\uA92F' => EastAsianWidthType.Neutral,
				>= '\uA930' and <= '\uA946' => EastAsianWidthType.Neutral,
				>= '\uA947' and <= '\uA951' => EastAsianWidthType.Neutral,
				>= '\uA952' and <= '\uA953' => EastAsianWidthType.Neutral,
				'\uA95F' => EastAsianWidthType.Neutral,
				>= '\uA960' and <= '\uA97C' => EastAsianWidthType.Wide,
				>= '\uA980' and <= '\uA982' => EastAsianWidthType.Neutral,
				'\uA983' => EastAsianWidthType.Neutral,
				>= '\uA984' and <= '\uA9B2' => EastAsianWidthType.Neutral,
				'\uA9B3' => EastAsianWidthType.Neutral,
				>= '\uA9B4' and <= '\uA9B5' => EastAsianWidthType.Neutral,
				>= '\uA9B6' and <= '\uA9B9' => EastAsianWidthType.Neutral,
				>= '\uA9BA' and <= '\uA9BB' => EastAsianWidthType.Neutral,
				>= '\uA9BC' and <= '\uA9BD' => EastAsianWidthType.Neutral,
				>= '\uA9BE' and <= '\uA9C0' => EastAsianWidthType.Neutral,
				>= '\uA9C1' and <= '\uA9CD' => EastAsianWidthType.Neutral,
				'\uA9CF' => EastAsianWidthType.Neutral,
				>= '\uA9D0' and <= '\uA9D9' => EastAsianWidthType.Neutral,
				>= '\uA9DE' and <= '\uA9DF' => EastAsianWidthType.Neutral,
				>= '\uA9E0' and <= '\uA9E4' => EastAsianWidthType.Neutral,
				'\uA9E5' => EastAsianWidthType.Neutral,
				'\uA9E6' => EastAsianWidthType.Neutral,
				>= '\uA9E7' and <= '\uA9EF' => EastAsianWidthType.Neutral,
				>= '\uA9F0' and <= '\uA9F9' => EastAsianWidthType.Neutral,
				>= '\uA9FA' and <= '\uA9FE' => EastAsianWidthType.Neutral,
				>= '\uAA00' and <= '\uAA28' => EastAsianWidthType.Neutral,
				>= '\uAA29' and <= '\uAA2E' => EastAsianWidthType.Neutral,
				>= '\uAA2F' and <= '\uAA30' => EastAsianWidthType.Neutral,
				>= '\uAA31' and <= '\uAA32' => EastAsianWidthType.Neutral,
				>= '\uAA33' and <= '\uAA34' => EastAsianWidthType.Neutral,
				>= '\uAA35' and <= '\uAA36' => EastAsianWidthType.Neutral,
				>= '\uAA40' and <= '\uAA42' => EastAsianWidthType.Neutral,
				'\uAA43' => EastAsianWidthType.Neutral,
				>= '\uAA44' and <= '\uAA4B' => EastAsianWidthType.Neutral,
				'\uAA4C' => EastAsianWidthType.Neutral,
				'\uAA4D' => EastAsianWidthType.Neutral,
				>= '\uAA50' and <= '\uAA59' => EastAsianWidthType.Neutral,
				>= '\uAA5C' and <= '\uAA5F' => EastAsianWidthType.Neutral,
				>= '\uAA60' and <= '\uAA6F' => EastAsianWidthType.Neutral,
				'\uAA70' => EastAsianWidthType.Neutral,
				>= '\uAA71' and <= '\uAA76' => EastAsianWidthType.Neutral,
				>= '\uAA77' and <= '\uAA79' => EastAsianWidthType.Neutral,
				'\uAA7A' => EastAsianWidthType.Neutral,
				'\uAA7B' => EastAsianWidthType.Neutral,
				'\uAA7C' => EastAsianWidthType.Neutral,
				'\uAA7D' => EastAsianWidthType.Neutral,
				>= '\uAA7E' and <= '\uAA7F' => EastAsianWidthType.Neutral,
				>= '\uAA80' and <= '\uAAAF' => EastAsianWidthType.Neutral,
				'\uAAB0' => EastAsianWidthType.Neutral,
				'\uAAB1' => EastAsianWidthType.Neutral,
				>= '\uAAB2' and <= '\uAAB4' => EastAsianWidthType.Neutral,
				>= '\uAAB5' and <= '\uAAB6' => EastAsianWidthType.Neutral,
				>= '\uAAB7' and <= '\uAAB8' => EastAsianWidthType.Neutral,
				>= '\uAAB9' and <= '\uAABD' => EastAsianWidthType.Neutral,
				>= '\uAABE' and <= '\uAABF' => EastAsianWidthType.Neutral,
				'\uAAC0' => EastAsianWidthType.Neutral,
				'\uAAC1' => EastAsianWidthType.Neutral,
				'\uAAC2' => EastAsianWidthType.Neutral,
				>= '\uAADB' and <= '\uAADC' => EastAsianWidthType.Neutral,
				'\uAADD' => EastAsianWidthType.Neutral,
				>= '\uAADE' and <= '\uAADF' => EastAsianWidthType.Neutral,
				>= '\uAAE0' and <= '\uAAEA' => EastAsianWidthType.Neutral,
				'\uAAEB' => EastAsianWidthType.Neutral,
				>= '\uAAEC' and <= '\uAAED' => EastAsianWidthType.Neutral,
				>= '\uAAEE' and <= '\uAAEF' => EastAsianWidthType.Neutral,
				>= '\uAAF0' and <= '\uAAF1' => EastAsianWidthType.Neutral,
				'\uAAF2' => EastAsianWidthType.Neutral,
				>= '\uAAF3' and <= '\uAAF4' => EastAsianWidthType.Neutral,
				'\uAAF5' => EastAsianWidthType.Neutral,
				'\uAAF6' => EastAsianWidthType.Neutral,
				>= '\uAB01' and <= '\uAB06' => EastAsianWidthType.Neutral,
				>= '\uAB09' and <= '\uAB0E' => EastAsianWidthType.Neutral,
				>= '\uAB11' and <= '\uAB16' => EastAsianWidthType.Neutral,
				>= '\uAB20' and <= '\uAB26' => EastAsianWidthType.Neutral,
				>= '\uAB28' and <= '\uAB2E' => EastAsianWidthType.Neutral,
				>= '\uAB30' and <= '\uAB5A' => EastAsianWidthType.Neutral,
				'\uAB5B' => EastAsianWidthType.Neutral,
				>= '\uAB5C' and <= '\uAB5F' => EastAsianWidthType.Neutral,
				>= '\uAB60' and <= '\uAB67' => EastAsianWidthType.Neutral,
				>= '\uAB70' and <= '\uABBF' => EastAsianWidthType.Neutral,
				>= '\uABC0' and <= '\uABE2' => EastAsianWidthType.Neutral,
				>= '\uABE3' and <= '\uABE4' => EastAsianWidthType.Neutral,
				'\uABE5' => EastAsianWidthType.Neutral,
				>= '\uABE6' and <= '\uABE7' => EastAsianWidthType.Neutral,
				'\uABE8' => EastAsianWidthType.Neutral,
				>= '\uABE9' and <= '\uABEA' => EastAsianWidthType.Neutral,
				'\uABEB' => EastAsianWidthType.Neutral,
				'\uABEC' => EastAsianWidthType.Neutral,
				'\uABED' => EastAsianWidthType.Neutral,
				>= '\uABF0' and <= '\uABF9' => EastAsianWidthType.Neutral,
				>= '\uAC00' and <= '\uD7A3' => EastAsianWidthType.Wide,
				>= '\uD7B0' and <= '\uD7C6' => EastAsianWidthType.Neutral,
				>= '\uD7CB' and <= '\uD7FB' => EastAsianWidthType.Neutral,
				>= '\uD800' and <= '\uDB7F' => EastAsianWidthType.Neutral,
				>= '\uDB80' and <= '\uDBFF' => EastAsianWidthType.Neutral,
				>= '\uDC00' and <= '\uDFFF' => EastAsianWidthType.Neutral,
				>= '\uE000' and <= '\uF8FF' => EastAsianWidthType.Ambiguous,
				>= '\uF900' and <= '\uFA6D' => EastAsianWidthType.Wide,
				>= '\uFA6E' and <= '\uFA6F' => EastAsianWidthType.Wide,
				>= '\uFA70' and <= '\uFAD9' => EastAsianWidthType.Wide,
				>= '\uFADA' and <= '\uFAFF' => EastAsianWidthType.Wide,
				>= '\uFB00' and <= '\uFB06' => EastAsianWidthType.Neutral,
				>= '\uFB13' and <= '\uFB17' => EastAsianWidthType.Neutral,
				'\uFB1D' => EastAsianWidthType.Neutral,
				'\uFB1E' => EastAsianWidthType.Neutral,
				>= '\uFB1F' and <= '\uFB28' => EastAsianWidthType.Neutral,
				'\uFB29' => EastAsianWidthType.Neutral,
				>= '\uFB2A' and <= '\uFB36' => EastAsianWidthType.Neutral,
				>= '\uFB38' and <= '\uFB3C' => EastAsianWidthType.Neutral,
				'\uFB3E' => EastAsianWidthType.Neutral,
				>= '\uFB40' and <= '\uFB41' => EastAsianWidthType.Neutral,
				>= '\uFB43' and <= '\uFB44' => EastAsianWidthType.Neutral,
				>= '\uFB46' and <= '\uFB4F' => EastAsianWidthType.Neutral,
				>= '\uFB50' and <= '\uFBB1' => EastAsianWidthType.Neutral,
				>= '\uFBB2' and <= '\uFBC1' => EastAsianWidthType.Neutral,
				>= '\uFBD3' and <= '\uFD3D' => EastAsianWidthType.Neutral,
				'\uFD3E' => EastAsianWidthType.Neutral,
				'\uFD3F' => EastAsianWidthType.Neutral,
				>= '\uFD50' and <= '\uFD8F' => EastAsianWidthType.Neutral,
				>= '\uFD92' and <= '\uFDC7' => EastAsianWidthType.Neutral,
				>= '\uFDF0' and <= '\uFDFB' => EastAsianWidthType.Neutral,
				'\uFDFC' => EastAsianWidthType.Neutral,
				'\uFDFD' => EastAsianWidthType.Neutral,
				>= '\uFE00' and <= '\uFE0F' => EastAsianWidthType.Ambiguous,
				>= '\uFE10' and <= '\uFE16' => EastAsianWidthType.Wide,
				'\uFE17' => EastAsianWidthType.Wide,
				'\uFE18' => EastAsianWidthType.Wide,
				'\uFE19' => EastAsianWidthType.Wide,
				>= '\uFE20' and <= '\uFE2F' => EastAsianWidthType.Neutral,
				'\uFE30' => EastAsianWidthType.Wide,
				>= '\uFE31' and <= '\uFE32' => EastAsianWidthType.Wide,
				>= '\uFE33' and <= '\uFE34' => EastAsianWidthType.Wide,
				'\uFE35' => EastAsianWidthType.Wide,
				'\uFE36' => EastAsianWidthType.Wide,
				'\uFE37' => EastAsianWidthType.Wide,
				'\uFE38' => EastAsianWidthType.Wide,
				'\uFE39' => EastAsianWidthType.Wide,
				'\uFE3A' => EastAsianWidthType.Wide,
				'\uFE3B' => EastAsianWidthType.Wide,
				'\uFE3C' => EastAsianWidthType.Wide,
				'\uFE3D' => EastAsianWidthType.Wide,
				'\uFE3E' => EastAsianWidthType.Wide,
				'\uFE3F' => EastAsianWidthType.Wide,
				'\uFE40' => EastAsianWidthType.Wide,
				'\uFE41' => EastAsianWidthType.Wide,
				'\uFE42' => EastAsianWidthType.Wide,
				'\uFE43' => EastAsianWidthType.Wide,
				'\uFE44' => EastAsianWidthType.Wide,
				>= '\uFE45' and <= '\uFE46' => EastAsianWidthType.Wide,
				'\uFE47' => EastAsianWidthType.Wide,
				'\uFE48' => EastAsianWidthType.Wide,
				>= '\uFE49' and <= '\uFE4C' => EastAsianWidthType.Wide,
				>= '\uFE4D' and <= '\uFE4F' => EastAsianWidthType.Wide,
				>= '\uFE50' and <= '\uFE52' => EastAsianWidthType.Wide,
				>= '\uFE54' and <= '\uFE57' => EastAsianWidthType.Wide,
				'\uFE58' => EastAsianWidthType.Wide,
				'\uFE59' => EastAsianWidthType.Wide,
				'\uFE5A' => EastAsianWidthType.Wide,
				'\uFE5B' => EastAsianWidthType.Wide,
				'\uFE5C' => EastAsianWidthType.Wide,
				'\uFE5D' => EastAsianWidthType.Wide,
				'\uFE5E' => EastAsianWidthType.Wide,
				>= '\uFE5F' and <= '\uFE61' => EastAsianWidthType.Wide,
				'\uFE62' => EastAsianWidthType.Wide,
				'\uFE63' => EastAsianWidthType.Wide,
				>= '\uFE64' and <= '\uFE66' => EastAsianWidthType.Wide,
				'\uFE68' => EastAsianWidthType.Wide,
				'\uFE69' => EastAsianWidthType.Wide,
				>= '\uFE6A' and <= '\uFE6B' => EastAsianWidthType.Wide,
				>= '\uFE70' and <= '\uFE74' => EastAsianWidthType.Neutral,
				>= '\uFE76' and <= '\uFEFC' => EastAsianWidthType.Neutral,
				'\uFEFF' => EastAsianWidthType.Neutral,
				>= '\uFF01' and <= '\uFF03' => EastAsianWidthType.FullWidth,
				'\uFF04' => EastAsianWidthType.FullWidth,
				>= '\uFF05' and <= '\uFF07' => EastAsianWidthType.FullWidth,
				'\uFF08' => EastAsianWidthType.FullWidth,
				'\uFF09' => EastAsianWidthType.FullWidth,
				'\uFF0A' => EastAsianWidthType.FullWidth,
				'\uFF0B' => EastAsianWidthType.FullWidth,
				'\uFF0C' => EastAsianWidthType.FullWidth,
				'\uFF0D' => EastAsianWidthType.FullWidth,
				>= '\uFF0E' and <= '\uFF0F' => EastAsianWidthType.FullWidth,
				>= '\uFF10' and <= '\uFF19' => EastAsianWidthType.FullWidth,
				>= '\uFF1A' and <= '\uFF1B' => EastAsianWidthType.FullWidth,
				>= '\uFF1C' and <= '\uFF1E' => EastAsianWidthType.FullWidth,
				>= '\uFF1F' and <= '\uFF20' => EastAsianWidthType.FullWidth,
				>= '\uFF21' and <= '\uFF3A' => EastAsianWidthType.FullWidth,
				'\uFF3B' => EastAsianWidthType.FullWidth,
				'\uFF3C' => EastAsianWidthType.FullWidth,
				'\uFF3D' => EastAsianWidthType.FullWidth,
				'\uFF3E' => EastAsianWidthType.FullWidth,
				'\uFF3F' => EastAsianWidthType.FullWidth,
				'\uFF40' => EastAsianWidthType.FullWidth,
				>= '\uFF41' and <= '\uFF5A' => EastAsianWidthType.FullWidth,
				'\uFF5B' => EastAsianWidthType.FullWidth,
				'\uFF5C' => EastAsianWidthType.FullWidth,
				'\uFF5D' => EastAsianWidthType.FullWidth,
				'\uFF5E' => EastAsianWidthType.FullWidth,
				'\uFF5F' => EastAsianWidthType.FullWidth,
				'\uFF60' => EastAsianWidthType.FullWidth,
				'\uFF61' => EastAsianWidthType.HalfWidth,
				'\uFF62' => EastAsianWidthType.HalfWidth,
				'\uFF63' => EastAsianWidthType.HalfWidth,
				>= '\uFF64' and <= '\uFF65' => EastAsianWidthType.HalfWidth,
				>= '\uFF66' and <= '\uFF6F' => EastAsianWidthType.HalfWidth,
				'\uFF70' => EastAsianWidthType.HalfWidth,
				>= '\uFF71' and <= '\uFF9D' => EastAsianWidthType.HalfWidth,
				>= '\uFF9E' and <= '\uFF9F' => EastAsianWidthType.HalfWidth,
				>= '\uFFA0' and <= '\uFFBE' => EastAsianWidthType.HalfWidth,
				>= '\uFFC2' and <= '\uFFC7' => EastAsianWidthType.HalfWidth,
				>= '\uFFCA' and <= '\uFFCF' => EastAsianWidthType.HalfWidth,
				>= '\uFFD2' and <= '\uFFD7' => EastAsianWidthType.HalfWidth,
				>= '\uFFDA' and <= '\uFFDC' => EastAsianWidthType.HalfWidth,
				>= '\uFFE0' and <= '\uFFE1' => EastAsianWidthType.FullWidth,
				'\uFFE2' => EastAsianWidthType.FullWidth,
				'\uFFE3' => EastAsianWidthType.FullWidth,
				'\uFFE4' => EastAsianWidthType.FullWidth,
				>= '\uFFE5' and <= '\uFFE6' => EastAsianWidthType.FullWidth,
				'\uFFE8' => EastAsianWidthType.HalfWidth,
				>= '\uFFE9' and <= '\uFFEC' => EastAsianWidthType.HalfWidth,
				>= '\uFFED' and <= '\uFFEE' => EastAsianWidthType.HalfWidth,
				>= '\uFFF9' and <= '\uFFFB' => EastAsianWidthType.Neutral,
				'\uFFFC' => EastAsianWidthType.Neutral,
				'\uFFFD' => EastAsianWidthType.Ambiguous,
				_ => EastAsianWidthType.Invalid
			};
		}
	}
}
