//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DisposableBase_ObjectDisposedException_IsDisposing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DisposableBase_ObjectDisposedException_IsDisposing {
            get {
                return ResourceManager.GetString("DisposableBase_ObjectDisposedException_IsDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidNodeNameException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidNodeNameException {
            get {
                return ResourceManager.GetString("InvalidNodeNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YArray_GetNode_ArgumentOutOfRangeException {0} {1} {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YArray_GetNode_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("YArray_GetNode_ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YArray_GetNode_NullReferenceException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YArray_GetNode_NullReferenceException {
            get {
                return ResourceManager.GetString("YArray_GetNode_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YenconException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YenconException {
            get {
                return ResourceManager.GetString("YenconException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YNode_ArgumentException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YNode_ArgumentException {
            get {
                return ResourceManager.GetString("YNode_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YNode_ArgumentNullException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YNode_ArgumentNullException {
            get {
                return ResourceManager.GetString("YNode_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YSection_GetNode_KeyNotFoundException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YSection_GetNode_KeyNotFoundException {
            get {
                return ResourceManager.GetString("YSection_GetNode_KeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YSection_GetNode_NullReferenceException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YSection_GetNode_NullReferenceException {
            get {
                return ResourceManager.GetString("YSection_GetNode_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   YSection_KeyNameEnumerator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YSection_KeyNameEnumerator {
            get {
                return ResourceManager.GetString("YSection_KeyNameEnumerator", resourceCulture);
            }
        }
    }
}
