//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exrecodel.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exrecodel.Properties.HtmlTexts", typeof(HtmlTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ContactInfo_address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_address {
            get {
                return ResourceManager.GetString("ContactInfo_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_address_PostCode {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_address_PostCode {
            get {
                return ResourceManager.GetString("ContactInfo_address_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_email {
            get {
                return ResourceManager.GetString("ContactInfo_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_fax に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_fax {
            get {
                return ResourceManager.GetString("ContactInfo_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_link に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_link {
            get {
                return ResourceManager.GetString("ContactInfo_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_sms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_sms {
            get {
                return ResourceManager.GetString("ContactInfo_sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_sns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_sns {
            get {
                return ResourceManager.GetString("ContactInfo_sns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_sns_ServiceProvider {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_sns_Provider {
            get {
                return ResourceManager.GetString("ContactInfo_sns_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContactInfo_tel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContactInfo_tel {
            get {
                return ResourceManager.GetString("ContactInfo_tel", resourceCulture);
            }
        }
    }
}
