//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exrecodel.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exrecodel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;!DOCTYPE xsd:schema&gt;
        ///&lt;!--*
        /// * Exrecodel - &quot;Extensible Regulation/Convention Descriptor Language&quot;
        /// *    「拡張可能な規則/規約記述言語」
        /// * Copyright (C) 2020 Takym.
        /// * 
        /// * distributed under the MIT License.
        ///**--&gt;
        ///&lt;xsd:schema
        ///	id=&quot;Exrecodel&quot;
        ///	targetNamespace=&quot;Exrecodel.xsd&quot;
        ///	elementFormDefault=&quot;qualified&quot;
        ///	xmlns:tns=&quot;Exrecodel.xsd&quot;
        ///	xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;xsd:complexType name=&quot;node&quot;&gt;
        ///		&lt;x [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XmlSchema {
            get {
                return ResourceManager.GetString("XmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlAddressInfo_Format {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlAddressInfo_Format {
            get {
                return ResourceManager.GetString("XrcdlAddressInfo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlAddressInfo_NoZipCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlAddressInfo_NoZipCode {
            get {
                return ResourceManager.GetString("XrcdlAddressInfo_NoZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlContactInformation_Name_InvalidOperationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlContactInformation_Name_InvalidOperationException {
            get {
                return ResourceManager.GetString("XrcdlContactInformation_Name_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlContactInformationEnumerator_InvalidOperationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlContactInformationEnumerator_InvalidOperationException {
            get {
                return ResourceManager.GetString("XrcdlContactInformationEnumerator_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlDocument_Load_InvalidDataException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlDocument_Load_InvalidDataException {
            get {
                return ResourceManager.GetString("XrcdlDocument_Load_InvalidDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlDocument_Load_InvalidOperationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlDocument_Load_InvalidOperationException {
            get {
                return ResourceManager.GetString("XrcdlDocument_Load_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlDocument_Load_IOException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlDocument_Load_IOException {
            get {
                return ResourceManager.GetString("XrcdlDocument_Load_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlDocument_Save_InvalidDataException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlDocument_Save_InvalidDataException {
            get {
                return ResourceManager.GetString("XrcdlDocument_Save_InvalidDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlDocument_Save_InvalidOperationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlDocument_Save_InvalidOperationException {
            get {
                return ResourceManager.GetString("XrcdlDocument_Save_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlDocument_Save_IOException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlDocument_Save_IOException {
            get {
                return ResourceManager.GetString("XrcdlDocument_Save_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlDocumentImplementation_LoadCore_XmlSchemaException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlDocumentImplementation_LoadCore_XmlSchemaException {
            get {
                return ResourceManager.GetString("XrcdlDocumentImplementation_LoadCore_XmlSchemaException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlEmailInfo_Format {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlEmailInfo_Format {
            get {
                return ResourceManager.GetString("XrcdlEmailInfo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlLinkInfo_Format {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlLinkInfo_Format {
            get {
                return ResourceManager.GetString("XrcdlLinkInfo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlLinkInfo_NoTitle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlLinkInfo_NoTitle {
            get {
                return ResourceManager.GetString("XrcdlLinkInfo_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlPhoneNumberInfo_Format {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlPhoneNumberInfo_Format {
            get {
                return ResourceManager.GetString("XrcdlPhoneNumberInfo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlPhoneNumberInfo_Format_Facsimile {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlPhoneNumberInfo_Format_Facsimile {
            get {
                return ResourceManager.GetString("XrcdlPhoneNumberInfo_Format_Facsimile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlPhoneNumberInfo_Format_ShortMessageService {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlPhoneNumberInfo_Format_ShortMessageService {
            get {
                return ResourceManager.GetString("XrcdlPhoneNumberInfo_Format_ShortMessageService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlPhoneNumberInfo_Format_Telephone {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlPhoneNumberInfo_Format_Telephone {
            get {
                return ResourceManager.GetString("XrcdlPhoneNumberInfo_Format_Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlPhoneNumberInfo_Normalize_FormatException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlPhoneNumberInfo_Normalize_FormatException {
            get {
                return ResourceManager.GetString("XrcdlPhoneNumberInfo_Normalize_FormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlSocialAccountInfo_Format {0} {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlSocialAccountInfo_Format {
            get {
                return ResourceManager.GetString("XrcdlSocialAccountInfo_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XrcdlSocialAccountInfo_NoServiceName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XrcdlSocialAccountInfo_NoServiceName {
            get {
                return ResourceManager.GetString("XrcdlSocialAccountInfo_NoServiceName", resourceCulture);
            }
        }
    }
}
