//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakymLibTests.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TakymLibTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   
        ///ManualBuilder_Build_Switch_Options /A
        ///  -a        --option-a
        ///  -b        --option-b
        ///  -c        --option-c
        ///            --long-option
        ///
        ///ManualBuilder_Build_Switch_Desc /B
        ///  test switch
        ///ManualBuilder_Build_Switch_Options /B
        ///  -a        --option-a                test option A
        ///  -b        --option-b                test option B
        ///  -c        --option-c                test option C
        ///            --long-option             test long option
        ///
        ///ManualBuilder_Build_Switch_Options /C
        ///  -a        --option-a
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CL_ManualBuilder_Result {
            get {
                return ResourceManager.GetString("CL_ManualBuilder_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C:\aaa\bbb\ccc\\ccc\\123.xyz\\123\\C:\aaa\bbb\ccc\123.xyz\\C:\aaa\bbb\ccc\123.xyz\\C:\\\file:///C:/aaa/bbb/ccc/123.xyz\\.xyz\\ABCD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathStringToStringResult {
            get {
                return ResourceManager.GetString("PathStringToStringResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///    !&quot;#$%&amp;&apos;()*+,-./0123456789:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveControlCharsTests_0 {
            get {
                return ResourceManager.GetString("RemoveControlCharsTests_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [NUL][SOH][STX][ETX][EOT][ENQ][ACK][BEL][BS]	[LF][VT][FF][CR][SO][SI][DLE][DC1][DC2][DC3][DC4][NAK][SYN][ETB][CAN][EM][SUB][ESC][FS][GS][RS][US] !&quot;#$%&amp;&apos;()*+,-./0123456789:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~[DEL][&lt;control-0080&gt;][&lt;control-0081&gt;][&lt;control-0082&gt;][&lt;control-0083&gt;][&lt;control-0084&gt;][&lt;control-0085&gt;][&lt;control-0086&gt;][CUS][NSB][NSE][FIL][PLD][PLU][ZWJ][ZWNJ][SS3][&lt;control-0090&gt;][EAB][EAE][ISB][ISE][SIB][SIE][SSB][SSE][INC][&lt;control-009A&gt;][&lt;control-009B&gt;][KWB][KWE][PSB][P [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveControlCharsTests_1 {
            get {
                return ResourceManager.GetString("RemoveControlCharsTests_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ␀␁␂␃␄␅␆␇␈	␊␋␌␍␎␏␐␑␒␓␔␕␖␗␘␙␚␛␜␝␞␟ !&quot;#$%&amp;&apos;()*+,-./0123456789:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~␡␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveControlCharsTests_2 {
            get {
                return ResourceManager.GetString("RemoveControlCharsTests_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [NUL][SOH][STX][ETX][EOT][ENQ][ACK][BEL][BS][TAB][LF][VT][FF][CR][SO][SI][DLE][DC1][DC2][DC3][DC4][NAK][SYN][ETB][CAN][EM][SUB][ESC][FS][GS][RS][US][SPh]!&quot;#$%&amp;&apos;()*+,-./0123456789:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~[DEL][&lt;control-0080&gt;][&lt;control-0081&gt;][&lt;control-0082&gt;][&lt;control-0083&gt;][&lt;control-0084&gt;][&lt;control-0085&gt;][&lt;control-0086&gt;][CUS][NSB][NSE][FIL][TCI][ICI][OSC][SS2][SS3][&lt;control-0090&gt;][EAB][EAE][ISB][ISE][SIB][SIE][SSB][SSE][INC][&lt;control-009A&gt;][&lt;control-009B&gt;][KWB][KWE] [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveControlCharsTests_3 {
            get {
                return ResourceManager.GetString("RemoveControlCharsTests_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ␀␁␂␃␄␅␆␇␈␣␊␋␌␍␎␏␐␑␒␓␔␕␖␗␘␙␚␛␜␝␞␟␠!&quot;#$%&amp;&apos;()*+,-./0123456789:;&lt;=&gt;?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~␡␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥␥ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RemoveControlCharsTests_4 {
            get {
                return ResourceManager.GetString("RemoveControlCharsTests_4", resourceCulture);
            }
        }
    }
}
