//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exrecodel.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exrecodel.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;contacts&quot; id=&quot;contacts&quot;&gt;&lt;h3&gt;ContactList&lt;/h3&gt;&lt;address class=&quot;address&quot;&gt;&lt;h4&gt;ContactInfo_address&lt;/h4&gt;&lt;p&gt;XYZ&lt;/p&gt;&lt;/address&gt;&lt;address class=&quot;address&quot;&gt;&lt;h4&gt;ContactInfo_address&lt;/h4&gt;&lt;p&gt;ABCDEF&lt;/p&gt;&lt;p&gt;ContactInfo_address_PostCode &lt;code&gt;1234&lt;/code&gt;&lt;/p&gt;&lt;/address&gt;&lt;address class=&quot;email&quot;&gt;&lt;h4&gt;ContactInfo_email&lt;/h4&gt;&lt;p&gt;&lt;a href=&quot;mailto:abcd@example.com&quot;&gt;abcd@example.com&lt;/a&gt;&lt;/p&gt;&lt;/address&gt;&lt;address class=&quot;email&quot;&gt;&lt;h4&gt;ContactInfo_email&lt;/h4&gt;&lt;p&gt;&lt;a href=&quot;mailto:abcd@example.com?subject=件名&amp;body=本文&quot;&gt;abcd@example.com&lt;/a&gt;&lt;/p&gt;&lt;/add [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HtmlConverterResult {
            get {
                return ResourceManager.GetString("HtmlConverterResult", resourceCulture);
            }
        }
    }
}
